Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2020-12, with the labels that each got.

#131 doc: Update CUPS API Key info
  doc/content/gateways/lora-basics-station/cups.md
  doc/content/gateways/lora-basics-station/troubleshooting.md
Labels: documentation, quickfix

#41 Mark application server linking as removed
  doc/content/integrations/adding-applications/_index.md
  doc/content/reference/components/application-server.md
  doc/content/reference/configuration/application-server.md
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/layouts/shortcodes/removed-in-version.html
Labels: c/application server

#28 doc: Add api curl examples
  doc/content/getting-started/api/_index.md
  doc/content/reference/api/_index.md
  doc/content/reference/api/field-mask.md
Labels: documentation

#128 doc: Update ThingSpeak guide
  doc/content/integrations/cloud-integrations/thingspeak/_index.md
  doc/content/integrations/cloud-integrations/thingspeak/thingspeak-setup/_index.md
  doc/content/integrations/cloud-integrations/thingspeak/tts-setup/_index.md
Labels: documentation, s/in progress

#107 Issue/add deprecated short code
  CONTRIBUTING.md
  doc/archetypes/section-bundle/_index.md
  doc/content/integrations/pubsub/_index.md
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/layouts/_default/list.html
  doc/themes/the-things-stack/layouts/_default/single.html
  doc/themes/the-things-stack/layouts/partials/deprecated-in-version.html
  doc/themes/the-things-stack/layouts/partials/pages-cards.html
  doc/themes/the-things-stack/layouts/shortcodes/deprecated-in-version.html
Labels: documentation

#144 doc: Uncomment lets encrypt from docker-compose.yml
  doc/content/getting-started/installation/configuration/docker-compose-enterprise.yml
  doc/content/getting-started/installation/configuration/docker-compose-open-source.yml
Labels: documentation, quickfix

#138 doc: Add tenancy config to enterprise config file
  doc/content/getting-started/installation/configuration/_index.md
  doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml
  doc/content/getting-started/installation/running-the-stack.md
Labels: documentation

#142 Mark storage config as enterprise only
  doc/content/integrations/storage/configuration.md
Labels: documentation, quickfix

#143 doc: Update ThingsBoard integration doc
  doc/content/integrations/cloud-integrations/thingsboard/scheduling-downlinks/adding-link.png
  doc/content/integrations/cloud-integrations/thingsboard/scheduling-downlinks/integration-downlink-node.png
  doc/content/integrations/cloud-integrations/thingsboard/scheduling-downlinks/shared-attribute.png
  doc/content/integrations/cloud-integrations/thingsboard/thingsboard-setup/_index.md
  doc/content/integrations/cloud-integrations/thingsboard/thingsboard-setup/creating-integration.png
  doc/content/integrations/cloud-integrations/thingsboard/thingsboard-setup/downlink-converter.png
  doc/content/integrations/cloud-integrations/thingsboard/thingsboard-setup/uplink-converter.png
Labels: documentation

#145 Improve image display in docs
  doc/content/gateways/ciscowirelessgateway/_index.md
  doc/content/gateways/dragino-lps8/_index.md
  doc/content/gateways/dragino-lps8/dragino-lps8.jpg
  doc/content/gateways/laird-sentrius/_index.md
  doc/content/gateways/laird-sentrius/basic-station.png
  doc/content/gateways/laird-sentrius/eui-small.png
  doc/content/gateways/laird-sentrius/lbs.md
  doc/content/gateways/laird-sentrius/login.png
  doc/content/gateways/lorix-one/_index.md
  doc/content/gateways/lorix-one/lbs.md
  doc/content/gateways/lorix-one/lorix-one-login.png
  doc/content/gateways/lorix-one/lorix-one-lora-settings-forwarder-change-bs.png
  doc/content/gateways/lorix-one/lorix-one-lora-settings-forwarder-change-list.png
  doc/content/gateways/mikrotikrouterboard/_index.md
  doc/content/gateways/mikrotikrouterboard/public.png
  doc/content/gateways/multitechconduit-mlinux/_index.md
  doc/content/gateways/multitechconduit/_index.md
  doc/content/gateways/multitechconduit/cert-error.png
  doc/content/gateways/thethingskickstartergateway/ttkg-config-window.png
  doc/content/gateways/ursalinkug8x/_index.md
  doc/content/gateways/ursalinkug8x/compact.png
  doc/content/gateways/ursalinkug8x/login.png
  doc/content/gateways/ursalinkug8x/outdoor.png
  doc/content/gateways/ursalinkug8x/ursalink.jpg
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/assets/css/vendor/basicLightbox.min.scss
  doc/themes/the-things-stack/assets/js/theme.js
  doc/themes/the-things-stack/assets/js/vendor/basicLightbox.min.js
  doc/themes/the-things-stack/layouts/partials/footer.html
  doc/themes/the-things-stack/layouts/partials/pages-cards.html
Labels: dependencies, technical debt, ui/web

#151 Update TTS, TTN and TTI logos
  doc/themes/the-things-stack/static/img/TTES-logo.svg
  doc/themes/the-things-stack/static/img/TTI-logo.svg
  doc/themes/the-things-stack/static/img/TTN-logo.svg
  doc/themes/the-things-stack/static/img/TTS-logo.svg
Labels: documentation

#148 doc: Add multi-tenant OAuth note
  doc/content/getting-started/installation/running-the-stack.md
Labels: documentation, quickfix

#147 doc: Add localhost certificates note
  doc/content/getting-started/installation/certificates.md
  doc/content/getting-started/installation/configuration/_index.md
Labels: documentation, quickfix

#136 Add screenshot req to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#133 doc: Improve documentation of stack init
  doc/content/getting-started/aws/ecs/database-operations/_index.md
Labels: documentation

#152 util: Migration to thethingsindustries.com/docs
  Makefile
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/assets/js/theme.js
  doc/themes/the-things-stack/layouts/partials/nav.html
Labels: infrastructure

#157 util: Fix base url
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
Labels: bug

#156 Issue/update figures
  CONTRIBUTING.md
  doc/content/devices/generate-qr-code/_index.md
  doc/content/devices/generate-qr-code/qr-claiming.png
  doc/content/devices/generate-qr-code/qr-identification.png
  doc/content/getting-started/aws/ami/deployment-guide/_index.md
  doc/content/getting-started/aws/ecs/architecture/_index.md
  doc/content/getting-started/migrating/device-json.md
  doc/content/integrations/aws-iot/default/_index.md
  doc/content/integrations/aws-iot/default/architecture.md
  doc/content/integrations/cloud-integrations/akenza-core/akenza-setup/creating-device-type.png
  doc/content/integrations/cloud-integrations/akenza-core/akenza-setup/creating-device.png
  doc/content/integrations/cloud-integrations/akenza-core/akenza-setup/creating-domain.png
  doc/content/integrations/cloud-integrations/akenza-core/akenza-setup/quick-start.png
  doc/content/integrations/cloud-integrations/akenza-core/tts-setup/creating-webhook.png
  doc/content/integrations/cloud-integrations/datacake/datacake-setup/datacake-tti-adapter.png
  doc/content/integrations/cloud-integrations/datacake/tts-setup/tts-datacake-webhook.png
  doc/content/integrations/cloud-integrations/microsoft-azure/azure-setup/azure-services-dashboard.png
  doc/content/integrations/cloud-integrations/microsoft-azure/azure-setup/creating-a-function-app.png
  doc/content/integrations/cloud-integrations/microsoft-azure/azure-setup/http-trigger-function-code.png
  doc/content/integrations/cloud-integrations/microsoft-azure/azure-setup/http-trigger-function-creation.png
  doc/content/integrations/cloud-integrations/microsoft-azure/azure-setup/successfully-deployed-function-app.png
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/custom-tti-device.png
  doc/content/integrations/cloud-integrations/tagoio/tts-setup/creating-a-webhook.png
  doc/content/integrations/cloud-integrations/thingspeak/thingspeak-setup/api-key.png
  doc/content/integrations/cloud-integrations/thingspeak/tts-setup/creating-a-webhook.png
  doc/content/integrations/cloud-integrations/ubidots/ubidots-setup/creating-function.png
  doc/content/integrations/ifttt/ifttt-setup/choosing-a-service.png
  doc/content/integrations/ifttt/ifttt-setup/choosing-action-service.png
  doc/content/integrations/ifttt/ifttt-setup/naming-trigger.png
  doc/content/integrations/ifttt/ifttt-setup/webhooks-documentation-page.png
  doc/content/integrations/mqtt-clients/mqttbox/publish.png
  doc/content/integrations/mqtt-clients/mqttbox/subscribe.png
  doc/content/integrations/node-red/_index.md
  doc/content/integrations/pubsub/_index.md
  doc/content/integrations/webhooks/api-key-creation.png
  doc/content/reference/components/_index.md
Labels: documentation

#159 Fix time format in storage integration reference
  doc/content/integrations/storage/retrieve.md
Labels: bug, quickfix

#149 doc: Fix typo in glossary
  doc/data/glossary.yml
Labels: documentation, quickfix

#161 doc: Add value proposition to docs homepage
  doc/content/_index.html
Labels: documentation

#154 Rename Global Join Server to The Things Join Server
  doc/content/devices/claim-atecc608a/_index.md
  doc/content/devices/device-claiming/_index.md
  doc/content/devices/device-claiming/make-device-claimable.md
  doc/content/devices/end-device-templates/converting.md
  doc/content/devices/end-device-templates/mapping.md
  doc/content/getting-started/cloud-hosted/tti-join-server/_index.md
  doc/content/getting-started/cloud-hosted/tti-join-server/activate-devices-cloud-hosted.md
  doc/content/getting-started/cloud-hosted/tti-join-server/register-devices.md
  doc/content/integrations/aws-iot/default/_index.md
  doc/content/integrations/aws-iot/default/architecture.md
  doc/content/integrations/aws-iot/default/deployment-guide.md
Labels: documentation

#129 Extend Cayenne LPP example
  doc/content/integrations/payload-formatters/cayenne.md
Labels: documentation

#158 doc: Add location solved to available topics
  doc/content/integrations/mqtt/_index.md
  doc/content/integrations/mqtt/cloud-hosted.md
Labels: documentation

#163 doc: Remove global_conf warning from docs
  doc/content/gateways/semtech-udp-packet-forwarder/_index.md
Labels: documentation

#162 Quickfix for inline shortcodes breaking headings
  CONTRIBUTING.md
  doc/archetypes/section-bundle/_index.md
  doc/content/getting-started/installation/configuration/_index.md
  doc/content/integrations/aws-iot/_index.md
  doc/content/reference/configuration/application-server.md
  doc/content/reference/configuration/identity-server.md
  doc/content/reference/configuration/network-server.md
  doc/content/reference/configuration/the-things-stack.md
Labels: documentation, quickfix

#164 Fix Storage Integration HTTP API URL
  doc/content/integrations/storage/retrieve.md
Labels: quickfix

#165 doc: Add LoRa Cloud & Ubidots integration guide for LR1110
  doc/content/integrations/lr1110-geolocation/LR1110-location.png
  doc/content/integrations/lr1110-geolocation/LR1110.jpg
  doc/content/integrations/lr1110-geolocation/_index.md
  doc/content/integrations/lr1110-geolocation/add-device.png
  doc/content/integrations/lr1110-geolocation/create-map-widget.png
  doc/content/integrations/lr1110-geolocation/device-owner.png
  doc/content/integrations/lr1110-geolocation/lora-cloud-das.png
  doc/content/integrations/lr1110-geolocation/lora-cloud-integration.png
  doc/content/integrations/lr1110-geolocation/manage-tokens.png
  doc/content/integrations/lr1110-geolocation/ubidots-device.png
  doc/content/integrations/lr1110-geolocation/ubidots-integration.png
Labels: documentation

#167 doc: Fix broken download link
  doc/themes/the-things-stack/layouts/_default/list.html
  doc/themes/the-things-stack/layouts/_default/single.html
  doc/themes/the-things-stack/layouts/partials/distributions.html
  doc/themes/the-things-stack/layouts/shortcodes/distributions-inline.html
  doc/themes/the-things-stack/layouts/shortcodes/distributions.html
Labels: documentation, quickfix

#173 Add "Accept: text/event-stream" header to events API example curl command
  doc/content/getting-started/events/_index.md
Labels: quickfix

#166 Issue/rename sections
  doc/content/download.html
  doc/content/gateways/laird-sentrius/_index.md
  doc/content/gateways/laird-sentrius/lbs.md
  doc/content/gateways/lorix-one/lbs.md
  doc/content/gateways/lorix-one/udp.md
  doc/content/gateways/multitechconduit/_index.md
  doc/content/gateways/multitechconduit/lbs.md
  doc/content/gateways/multitechconduit/udp.md
  doc/content/gateways/ursalinkug8x/_index.md
  doc/content/gateways/ursalinkug8x/lbs.md
  doc/content/gateways/ursalinkug8x/packet-forwarder.md
  doc/content/integrations/adding-integrations/_index.md
  doc/content/integrations/cloud-integrations/akenza-core/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/datacake/scheduling-downlinks/_index.md
  doc/content/integrations/cloud-integrations/datacake/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/influxdb-cloud/telegraf-setup/telegraf-http-setup.md
  doc/content/integrations/cloud-integrations/influxdb-cloud/telegraf-setup/telegraf-mqtt-setup.md
  doc/content/integrations/cloud-integrations/microsoft-azure/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/tagoio/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/thingsboard/scheduling-downlinks/_index.md
  doc/content/integrations/cloud-integrations/thingsboard/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/thingspeak/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/ubidots/_index.md
  doc/content/integrations/cloud-integrations/ubidots/tts-setup/_index.md
  doc/content/integrations/ifttt/_index.md
  doc/content/integrations/ifttt/node-red-setup/_index.md
  doc/content/integrations/ifttt/tts-setup/_index.md
  doc/content/integrations/mqtt-clients/_index.md
  doc/content/integrations/mqtt/_index.md
  doc/content/integrations/node-red/_index.md
Labels: documentation

#175 doc: Cross-referencing integration guides
  doc/content/getting-started/aws/_index.md
  doc/content/integrations/adding-integrations/_index.md
  doc/content/integrations/aws-iot/_index.md
Labels: documentation

#172 doc: Add Tektelic Basic Station guide
  doc/content/gateways/tektelickonamicro/_index.md
  doc/content/gateways/tektelickonamicro/kona-micro.jpg
  doc/content/gateways/tektelickonamicro/lbs.md
  doc/content/gateways/tektelickonamicro/udp.md
Labels: documentation

#116 Doc/improve installation guide
  doc/content/getting-started/installation/_index.md
  doc/content/getting-started/installation/certificates.md
  doc/content/getting-started/installation/configuration/_index.md
  doc/content/getting-started/installation/running-the-stack.md
  doc/content/getting-started/installation/troubleshooting.md
Labels: documentation

#187 Update AWS IoT Core Integration diagram
  doc/content/integrations/aws-iot/default/architecture.svg
Labels: quickfix
