Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2020-11, with the labels that each got.

#55 doc: Improving AWS IoT diagram
  doc/content/integrations/aws-iot/default/overview.svg
Labels: documentation

#61 Document Telemetry
  doc/content/getting-started/aws/_index.md
  doc/content/getting-started/aws/ami/_index.md
  doc/content/getting-started/aws/ecs/_index.md
  doc/content/getting-started/aws/ecs/deployment/_index.md
  doc/content/getting-started/aws/ecs/monitoring/_index.md
  doc/content/reference/telemetry/_index.md
Labels: c/shared

#65 doc: Rename troubleshooting sections
  CONTRIBUTING.md
  doc/archetypes/section-bundle/troubleshooting.md
  doc/content/gateways/kerlinkwirnetstation/_index.md
  doc/content/gateways/lora-basics-station/troubleshooting.md
  doc/content/getting-started/aws/ami/troubleshooting/_index.md
  doc/content/getting-started/installation/troubleshooting.md
  doc/content/integrations/aws-iot/default/troubleshooting.md
Labels: documentation

#36 doc: Add troubleshooting
  doc/content/getting-started/troubleshooting/_index.md
Labels: documentation

#66 doc: Rename troubleshooting (again)
  doc/content/devices/adding-devices/troubleshooting.md
  doc/content/gateways/adding-gateways/troubleshooting.md
  doc/content/getting-started/troubleshooting/_index.md
Labels: documentation

#26 doc: Add multitech basic station guide
  doc/content/gateways/multitechconduit/007_Channel_Plan.png
  doc/content/gateways/multitechconduit/008_Server_Setup_Configuration.png
  doc/content/gateways/multitechconduit/017_001_Gateway_Menu_LoRaWAN.png
  doc/content/gateways/multitechconduit/017_002_Gateway_Menu_Save-And-Restart.png
  doc/content/gateways/multitechconduit/018_Packet_Forwarder_Gateway.png
  doc/content/gateways/multitechconduit/019_Channel_Plan.png
  doc/content/gateways/multitechconduit/020_Server_Setup_Configuration.png
  doc/content/gateways/multitechconduit/023_System_Confirmation_Prompt.png
  doc/content/gateways/multitechconduit/024_Firmware_Upgrade.png
  doc/content/gateways/multitechconduit/028_Packet_Forwarder.png
  doc/content/gateways/multitechconduit/_index.md
  doc/content/gateways/multitechconduit/access-save.png
  doc/content/gateways/multitechconduit/access.png
  doc/content/gateways/multitechconduit/cert-error.png
  doc/content/gateways/multitechconduit/confirm.png
  doc/content/gateways/multitechconduit/eth.png
  doc/content/gateways/multitechconduit/firmware-upgrade.png
  doc/content/gateways/multitechconduit/first-time-setup.png
  doc/content/gateways/multitechconduit/lbs-cups.png
  doc/content/gateways/multitechconduit/lbs-menu.png
  doc/content/gateways/multitechconduit/lbs-save.png
  doc/content/gateways/multitechconduit/lbs.md
  doc/content/gateways/multitechconduit/main-menu.png
  doc/content/gateways/multitechconduit/manual-config-2.png
  doc/content/gateways/multitechconduit/manual-config.png
  doc/content/gateways/multitechconduit/multitech-conduit-ap.png
  doc/content/gateways/multitechconduit/multitech-conduit.png
  doc/content/gateways/multitechconduit/network-interfaces.png
  doc/content/gateways/multitechconduit/packet-forwarder-menu.png
  doc/content/gateways/multitechconduit/packet-forwarder.png
  doc/content/gateways/multitechconduit/save-and-restart.png
  doc/content/gateways/multitechconduit/time-date.png
  doc/content/gateways/multitechconduit/udp.md
Labels: documentation

#67 doc: Fix double sentences
  doc/content/integrations/adding-applications/_index.md
Labels: documentation

#58 Update API
  doc/data/api/ttn.lorawan.v3/enums.yml
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/api/ttn.lorawan.v3/services.yml
Labels: documentation

#52 doc: Add ThingSpeak integration guide
  doc/content/integrations/cloud-integrations/thingspeak/_index.md
  doc/content/integrations/cloud-integrations/thingspeak/thingspeak-setup/_index.md
  doc/content/integrations/cloud-integrations/thingspeak/thingspeak-setup/api-key.png
  doc/content/integrations/cloud-integrations/thingspeak/thingspeak-setup/channel.png
  doc/content/integrations/cloud-integrations/thingspeak/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/thingspeak/tts-setup/creating-a-webhook.png
Labels: documentation

#64 Fix old docs links in config
  doc/config/_default/config.toml
Labels: documentation, quickfix

#18 doc: Add udp packet forwarder doc
  doc/content/gateways/ciscowirelessgateway/_index.md
  doc/content/gateways/multitechconduit/udp.md
  doc/content/gateways/nasysoutdoorgateway/_index.md
  doc/content/gateways/semtech-udp-packet-forwarder/_index.md
  doc/content/gateways/semtech-udp-packet-forwarder/conf.png
  doc/themes/the-things-stack/layouts/shortcodes/udp-pf.html
Labels: documentation

#35 util: Add distribution instructions to CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation

#68 Add ES5 warning to payload formatter doc
  doc/content/integrations/payload-formatters/javascript.md
Labels: documentation

#15 doc: Storage Integration
  doc/content/getting-started/aws/ecs/deployment/_index.md
  doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml
  doc/content/getting-started/installation/running-the-stack.md
  doc/content/integrations/storage/_index.md
  doc/content/integrations/storage/configuration.md
  doc/content/integrations/storage/enable.md
  doc/content/integrations/storage/retrieve.md
  doc/content/reference/api/storage_integration.md
  doc/content/reference/configuration/application-server.md
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/api/ttn.lorawan.v3/services.yml
Labels: c/application server

#57 doc: Update documentation for device JSON objects
  doc/content/getting-started/migrating-from-networks/device-json.md
Labels: documentation

#69 Update guides from Cloud Integrations to use Webhook templates
  doc/content/integrations/cloud-integrations/akenza-core/akenza-setup/_index.md
  doc/content/integrations/cloud-integrations/akenza-core/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/akenza-core/tts-setup/creating-webhook.png
  doc/content/integrations/cloud-integrations/datacake/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/datacake/tts-setup/tts-datacake-webhook.png
  doc/content/integrations/cloud-integrations/tagoio/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/tagoio/tts-setup/creating-a-webhook.png
  doc/content/integrations/cloud-integrations/ubidots/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/ubidots/tts-setup/ubidots-webhook-creation.png
Labels: documentation

#80 Update CockroachDB command in Getting Started guide
  doc/content/getting-started/installation/configuration/docker-compose-enterprise.yml
  doc/content/getting-started/installation/configuration/docker-compose-open-source.yml
Labels: bug

#75 Update ES5 description
  CODEOWNERS
  doc/content/integrations/payload-formatters/javascript.md
Labels: documentation, quickfix

#81 doc: Add installation notes
  doc/content/getting-started/installation/configuration/_index.md
Labels: documentation

#38 Add localhost installation instructions
  doc/content/getting-started/installation/configuration/_index.md
  doc/content/getting-started/installation/running-the-stack.md
  doc/content/getting-started/installation/troubleshooting.md
Labels: documentation

#14 doc: Add AS end device fetcher cache configuration
  doc/content/reference/configuration/application-server.md
Labels: c/application server

#91 doc: Add global_conf bug note
  doc/content/gateways/semtech-udp-packet-forwarder/_index.md
Labels: documentation

#76 Add x overflow to content css
  doc/content/gateways/kerlinkwirnetistation/_index.md
  doc/content/gateways/kerlinkwirnetstation/_index.md
  doc/themes/the-things-stack/assets/css/theme.scss
Labels: documentation

#77 Make frequency plan ID prominent
  doc/content/reference/frequency-plans/_index.md
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/layouts/shortcodes/frequency-plans.html
  doc/themes/the-things-stack/layouts/shortcodes/frequency_plans.html
Labels: documentation

#98 doc: Update Kona Micro documentation link
  doc/content/gateways/tektelickonamicro/_index.md
Labels: documentation

#100 doc: Add lbs auth note
  doc/content/gateways/lora-basics-station/_index.md
  doc/content/gateways/lora-basics-station/cups.md
  doc/content/gateways/lora-basics-station/lns.md
Labels: documentation

#101 doc: Add v2 payload formatter note
  doc/content/integrations/payload-formatters/javascript.md
Labels: documentation

#103 doc: Add CUPS instructions
  doc/content/gateways/lora-basics-station/cups.md
  doc/content/gateways/lora-basics-station/lns.md
Labels: documentation

#78 doc: Add device claiming security session note
  doc/content/devices/device-claiming/_index.md
  doc/content/devices/device-claiming/claim-devices.md
Labels: documentation

#99 doc: Add V2 API note
  doc/content/reference/api/_index.md
Labels: documentation

#88 doc: Document ThingsBoard integration
  doc/content/integrations/cloud-integrations/thingsboard/_index.md
  doc/content/integrations/cloud-integrations/thingsboard/scheduling-downlinks/_index.md
  doc/content/integrations/cloud-integrations/thingsboard/scheduling-downlinks/adding-link.png
  doc/content/integrations/cloud-integrations/thingsboard/scheduling-downlinks/integration-downlink-node.png
  doc/content/integrations/cloud-integrations/thingsboard/scheduling-downlinks/shared-attribute.png
  doc/content/integrations/cloud-integrations/thingsboard/thingsboard-setup/_index.md
  doc/content/integrations/cloud-integrations/thingsboard/thingsboard-setup/creating-integration.png
  doc/content/integrations/cloud-integrations/thingsboard/thingsboard-setup/downlink-converter.png
  doc/content/integrations/cloud-integrations/thingsboard/thingsboard-setup/uplink-converter.png
  doc/content/integrations/cloud-integrations/thingsboard/tts-setup/_index.md
Labels: documentation

#111 Add @pierrephz as style/theme codeowner
  CODEOWNERS
Labels: tooling

#117 Fix/basic station
  doc/content/gateways/lora-basics-station/_index.md
  doc/content/gateways/lora-basics-station/troubleshooting.md
  doc/content/reference/api/gateway_server_mqtt.md
  doc/content/reference/components/gateway-configuration-server.md
  doc/content/reference/components/gateway-server.md
Labels: documentation

#105 doc: Update v2 migrations docs with info on CLI configuration
  doc/content/getting-started/migrating/migrating-from-v2.md
Labels: quickfix, ui/cli

#120 doc: Add cloud storage integration note
  doc/content/integrations/storage/configuration.md
Labels: documentation

#118 doc: Improving readability of AWS doc
  doc/content/getting-started/aws/_index.md
  doc/content/getting-started/aws/ami/deployment-guide/_index.md
  doc/content/getting-started/aws/ami/post-deployment/_index.md
  doc/content/getting-started/aws/ami/troubleshooting/_index.md
  doc/content/getting-started/aws/ecs/architecture/_index.md
  doc/content/getting-started/aws/ecs/database-operations/_index.md
  doc/content/getting-started/aws/ecs/deployment/_index.md
  doc/content/getting-started/aws/ecs/prerequisites/_index.md
Labels: documentation

#119 doc: Fix contributing link
  doc/content/_index.html
Labels: documentation

#123 doc: Update glossary with info on LoRaWAN versions
  doc/data/glossary.yml
Labels: quickfix

#124 Update configuration reference for trusted-proxies
  doc/content/reference/configuration/the-things-stack.md
Labels: c/shared

#24 doc: Add mlinux gateway guide
  doc/content/gateways/multitechconduit-mlinux/001_Multitech_Conduit.png
  doc/content/gateways/multitechconduit-mlinux/_index.md
Labels: documentation
