Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2020-10, with the labels that each got.

#13 util: Add git hooks
  .hooks/install-hooks.go
  .hooks/run-hooks.go
  Makefile
  README.md
  go.mod
  go.sum
Labels: tooling

#19 doc: Add console gcs config
  doc/content/reference/configuration/console.md
Labels: documentation

#20 doc: Update migration doc with import feature
  doc/content/getting-started/migrating-from-networks/_index.md
  doc/content/getting-started/migrating-from-networks/device-json.md
  doc/content/getting-started/migrating-from-networks/import-devices.md
  doc/content/getting-started/migrating-from-networks/import-end-devices.png
  doc/content/getting-started/migrating-from-networks/operation-finished.png
  doc/content/getting-started/migrating-from-networks/upload-file.png
  doc/content/getting-started/migrating-from-v2/_index.md
  doc/content/getting-started/migrating-from-v2/configure-ttn-lw-cli.md
  doc/content/getting-started/migrating-from-v2/create-application.md
  doc/content/getting-started/migrating-from-v2/export-v2-devices.md
  doc/content/getting-started/migrating-from-v2/import-devices.md
  doc/content/getting-started/migrating-from-v2/mqtt-api-comparison.md
Labels: documentation

#21 doc: Fix cups certificate ref
  doc/content/gateways/lora-basics-station/cups.md
Labels: quickfix

#22 doc: Add ISRG and DST root certs
  doc/content/reference/root-certificates/_index.md
Labels: documentation

#6 doc: Add keys to glossary
  doc/data/glossary.yml
Labels: documentation

#7 util: Add license and contributing
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: discussion, documentation

#9 doc: Document uplink message consumed airtime and location fields
  doc/content/getting-started/migrating-from-v2/mqtt-api-comparison.md
  doc/content/integrations/data-formats/_index.md
Labels: c/application server, c/network server

#8 doc: Update Datacake integration guide
  doc/content/integrations/cloud-integrations/datacake/datacake-setup/_index.md
  doc/content/integrations/cloud-integrations/datacake/datacake-setup/lorawan-settings.png
  doc/content/integrations/cloud-integrations/datacake/scheduling-downlinks/_index.md
  doc/content/integrations/cloud-integrations/datacake/scheduling-downlinks/downlink-configuration.png
  doc/content/integrations/cloud-integrations/datacake/tts-setup/_index.md
Labels: documentation

#34 util: Add line break style guidelines
  CONTRIBUTING.md
  doc/content/example-template/_index.md
Labels: documentation

#33 doc: Add archetype to easily create new docs
  CONTRIBUTING.md
  Makefile
  README.md
  doc/archetypes/section-bundle/_index.md
Labels: documentation

#32 doc: Replace doc link with ref
  doc/content/getting-started/migrating-from-v2/mqtt-api-comparison.md
Labels: documentation, quickfix

#27 doc: Add Chirpstack migration section to docs
  doc/content/getting-started/migrating-from-networks/device-json.md
  doc/content/getting-started/migrating-from-networks/import-devices.md
  doc/content/getting-started/migrating-from-networks/migrate-from-chirpstack.md
Labels: documentation

#31 util: Add build workflow
  .editorconfig
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .hooks/install-hooks.go
  Makefile
  doc/archetypes/section-bundle/_index.md
  doc/content/devices/claim-atecc608a/_index.md
  doc/content/devices/device-claiming/make-device-claimable.md
  doc/content/getting-started/aws/ami/troubleshooting/_index.md
  doc/content/getting-started/cli/installing-cli/_index.md
  doc/content/getting-started/cloud-hosted/_index.md
  doc/content/getting-started/cloud-hosted/tti-join-server/activate-devices-cloud-hosted.md
  doc/content/getting-started/migrating-from-networks/import-devices.md
  doc/content/getting-started/migrating-from-v2/_index.md
  doc/content/getting-started/migrating-from-v2/gateway-migration.md
  doc/content/integrations/cloud-integrations/datacake/datacake-setup/_index.md
  doc/content/integrations/cloud-integrations/datacake/scheduling-downlinks/_index.md
  doc/content/integrations/cloud-integrations/datacake/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/influxdb-cloud/telegraf-setup/telegraf-http-setup.md
  doc/content/integrations/cloud-integrations/influxdb-cloud/telegraf-setup/telegraf-mqtt-setup.md
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/_index.md
  doc/content/integrations/cloud-integrations/tagoio/tts-setup/_index.md
  doc/content/integrations/ifttt/ifttt-setup/_index.md
  doc/content/integrations/ifttt/tts-setup/_index.md
  doc/content/integrations/mqtt-clients/eclipse-paho/_index.md
  doc/content/integrations/mqtt-clients/hivemq/_index.md
  doc/content/integrations/mqtt/cloud-hosted.md
  doc/content/reference/configuration/the-things-stack.md
  doc/content/reference/root-certificates/_index.md
  doc/themes/the-things-stack/layouts/shortcodes/distributions-list.html
  doc/themes/the-things-stack/layouts/shortcodes/events.html
  doc/themes/the-things-stack/layouts/shortcodes/new-in-version.html
Labels: documentation

#43 Update config for thethingsstack.io and build workflow
  Makefile
  doc/config/_default/config.toml
  doc/config/_default/config.toml.tmpl
Labels: documentation

#23 Docs redesign
  doc/content/_index.html
  doc/static/favicon.ico
  doc/static/overview-clickable.svg
  doc/static/overview.svg
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/layouts/partials/file-info.html
  doc/themes/the-things-stack/layouts/partials/footer.html
  doc/themes/the-things-stack/layouts/partials/nav.html
  doc/themes/the-things-stack/static/fonts/Manrope-Extrabold.otf
  doc/themes/the-things-stack/static/fonts/Manrope-Extrabold.woff
  doc/themes/the-things-stack/static/fonts/Manrope-Extrabold.woff2
  doc/themes/the-things-stack/static/img/TTS-horizontal-logo.svg
  doc/themes/the-things-stack/static/img/search_bg.svg
Labels: documentation

#49 doc: Update TagoIO integration doc
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/_index.md
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/auth-pop-out.png
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/confirmation-window.png
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/custom-tti-device.png
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/custom-ttn-device.png
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/device-features.png
  doc/content/integrations/cloud-integrations/tagoio/tagoio-setup/device-settings.png
  doc/content/integrations/cloud-integrations/tagoio/tts-setup/_index.md
Labels: documentation
