Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-08, with the labels that each got.

#457 doc: Improve RAK docs
  doc/content/gateways/rak-7240/_index.md
  doc/content/gateways/rak-7240/bs.md
  doc/content/gateways/rak-7240/cups-lns.jpg
  doc/content/gateways/rak-7240/cups-lns.png
Labels: documentation

#463 Fix typo in TTIG gateway doc
  doc/content/gateways/thethingsindoorgateway/_index.md
Labels: documentation

#473 doc: Fix broken links in Glossary documentation
  doc/data/glossary.yml
Labels: documentation

#490 doc: Move packet broker docs
  doc/content/devices/abp-vs-otaa/_index.md
  doc/content/getting-started/migrating/configure-mac-settings.md
  doc/content/getting-started/migrating/major-changes.md
  doc/content/getting-started/migrating/migrating-from-v2/_index.md
  doc/content/getting-started/migrating/migrating-from-v2/packet-broker-requirements.md
  doc/content/getting-started/packet-broker/_index.md
  doc/content/getting-started/packet-broker/configure/_index.md
  doc/content/getting-started/packet-broker/configure/registration.md
  doc/content/getting-started/packet-broker/configure/routing-policies.md
  doc/content/getting-started/packet-broker/connect.md
  doc/content/getting-started/packet-broker/overview.png
Labels: documentation

#498 Fix homepage schema and 404 page
  doc/static/img/icon-application.svg
  doc/static/img/icon-device.svg
  doc/static/img/icon-gateway.svg
  doc/static/img/icon-integration.svg
  doc/static/img/icon-network-server.svg
  doc/themes/the-things-stack/assets/css/common/global.scss
  doc/themes/the-things-stack/assets/css/schema/schema.scss
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/layouts/404.html
  doc/themes/the-things-stack/layouts/index.html
  doc/themes/the-things-stack/layouts/partials/schema/icon.html
  doc/themes/the-things-stack/layouts/partials/schema/schema.html
Labels: documentation, needs/triage

#499 Add packetbroker TTN forwarding example
  doc/content/getting-started/packet-broker/configure/_index.md
  doc/content/getting-started/packet-broker/configure/registration.md
  doc/content/getting-started/packet-broker/configure/routing-policies.md
  doc/content/getting-started/packet-broker/connect.md
Labels: documentation

#500 Document supported QOS value for MQTT server
  doc/content/integrations/mqtt/_index.md
Labels: documentation, needs/triage

#503 Fix image links
  doc/themes/the-things-stack/layouts/partials/schema/schema.html
Labels: quickfix

#488 doc: Add AllThingsTalk integration guide
  doc/content/integrations/cloud-integrations/allthingstalk/actuator.png
  doc/content/integrations/cloud-integrations/allthingstalk/asset.png
  doc/content/integrations/cloud-integrations/allthingstalk/att-webhook.png
  doc/content/integrations/cloud-integrations/allthingstalk/device-settings.png
  doc/content/integrations/cloud-integrations/allthingstalk/ground.png
  doc/content/integrations/cloud-integrations/allthingstalk/index.md
  doc/content/integrations/cloud-integrations/allthingstalk/lora-device.png
  doc/content/integrations/cloud-integrations/allthingstalk/send-command.png
  doc/content/integrations/cloud-integrations/allthingstalk/sensor-data.png
  doc/content/integrations/cloud-integrations/allthingstalk/ttnv3.png
Labels: documentation

#487 Doc/cli troubleshooting
  doc/content/getting-started/cli/_index.md
  doc/content/getting-started/cli/installing-cli/_index.md
  doc/content/reference/cli/troubleshooting.md
Labels: documentation

#475 Improve description of field masks in API documentation
  doc/content/getting-started/api/_index.md
  doc/content/reference/api/_index.md
  doc/content/reference/api/application.md
  doc/content/reference/api/end_device.md
  doc/content/reference/api/events.md
  doc/content/reference/api/field-mask.md
  doc/content/reference/api/gateway.md
  doc/content/reference/api/gateway_server.md
  doc/content/reference/api/organization.md
  doc/content/reference/api/storage_integration.md
  doc/content/reference/api/user.md
  doc/themes/the-things-stack/layouts/shortcodes/proto/message.html
Labels: documentation

#506 doc: Add purge CLI commands
  doc/content/reference/purge/_index.md
Labels: documentation

#505 doc: Add disable storage integration instructions
  doc/content/integrations/storage/enable.md
Labels: documentation

#527 doc: Release v3.14.1 documentation update
  doc/content/whats-new/3.14.1.md
  doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.UserRights.yml
  doc/data/api/tti.lorawan.v3/messages/SearchTenantsRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/Application.yml
  doc/data/api/ttn.lorawan.v3/messages/CUPSRedirection.yml
  doc/data/api/ttn.lorawan.v3/messages/ClaimGatewayRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/Client.yml
  doc/data/api/ttn.lorawan.v3/messages/Gateway.yml
  doc/data/api/ttn.lorawan.v3/messages/IsConfiguration.UserRights.yml
  doc/data/api/ttn.lorawan.v3/messages/Organization.yml
  doc/data/api/ttn.lorawan.v3/messages/PacketBrokerInfo.yml
  doc/data/api/ttn.lorawan.v3/messages/PacketBrokerRegisterRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/SearchApplicationsRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/SearchClientsRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/SearchEndDevicesRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/SearchGatewaysRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/SearchOrganizationsRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/SearchUsersRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/User.yml
  doc/data/api/ttn.lorawan.v3/services/Pba.yml
  doc/data/ttn-lw-cli.yml
Labels: documentation, release

#526 doc: Add console purge screenshots
  doc/content/reference/purge/_index.md
  doc/content/reference/purge/delete.png
  doc/content/reference/purge/purge.png
Labels: documentation

#514 doc: Add glossary entries
  doc/data/glossary.yml
Labels: documentation

#523 doc: Clarify cli differences
  doc/content/getting-started/cli/installing-cli/_index.md
Labels: documentation

#533 doc: Note storage delay
  doc/content/integrations/storage/_index.md
Labels: documentation

#532 doc: Add gateway FAQ
  doc/content/gateways/troubleshooting/_index.md
Labels: documentation

#530 doc: Add entity taken error
  doc/content/getting-started/troubleshooting/_index.md
  doc/content/reference/purge/_index.md
Labels: documentation

#531 Update deps
  Makefile
  doc/data/frequency-plans.yml
  doc/yarn.lock
Labels: documentation

#524 doc: Add configuration options note
  doc/content/reference/configuration/_index.md
Labels: documentation

#525 doc: Add id and eui errors to gw troubleshooting
  doc/content/gateways/troubleshooting/_index.md
Labels: documentation

#504 doc: Add packet broker routing defaults table
  doc/content/getting-started/packet-broker/configure/routing-policies.md
  doc/content/reference/pb-routing/_index.md
Labels: documentation

#494 doc: Update adding devices doc for console changes
  doc/content/devices/adding-devices/_index.md
  doc/content/devices/adding-devices/advanced.png
  doc/content/devices/adding-devices/basic-settings.png
  doc/content/devices/adding-devices/class.png
  doc/content/devices/adding-devices/default-frequencies.png
  doc/content/devices/adding-devices/device-repo-settings.png
  doc/content/devices/adding-devices/external-servers.png
  doc/content/devices/adding-devices/join-settings.png
  doc/content/devices/adding-devices/manual-abp.png
  doc/content/devices/adding-devices/manual-network-settings-abp.png
  doc/content/devices/adding-devices/manual-network-settings-otaa.png
  doc/content/devices/adding-devices/manual-settings.png
  doc/content/devices/adding-devices/manual-tab.png
  doc/content/devices/adding-devices/manual.png
  doc/content/devices/adding-devices/network-settings.png
  doc/content/devices/adding-devices/register-manually.png
  doc/content/devices/adding-devices/rx1-settings.png
Labels: documentation

#518 doc: Document setting gateway antenna gain
  doc/content/gateways/adding-gateways/_index.md
Labels: documentation

#536 doc: Document tenant management
  doc/content/reference/tenant-management/_index.md
  doc/themes/the-things-stack/layouts/shortcodes/cli-only.html
Labels: documentation

#547 doc: Update v3.14.2 release docs
  doc/content/whats-new/3.14.2.md
  doc/data/api/ttn.lorawan.v3/messages/EndDeviceBrand.yml
  doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.FirmwareVersion.Profile.yml
  doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.FirmwareVersion.yml
  doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.Photos.yml
  doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.Reseller.yml
  doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.Videos.yml
  doc/data/api/ttn.lorawan.v3/messages/EndDeviceModel.yml
  doc/data/api/ttn.lorawan.v3/messages/GetEndDeviceBrandRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/GetEndDeviceModelRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/GetPayloadFormatterRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/GetStoredApplicationUpCountRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/GetStoredApplicationUpCountResponse.yml
  doc/data/api/ttn.lorawan.v3/messages/GetTemplateRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/LRFHSSDataRate.yml
  doc/data/api/ttn.lorawan.v3/messages/ListEndDeviceBrandsRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/ListEndDeviceModelsRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/MACSettings.yml
  doc/data/api/ttn.lorawan.v3/services/ApplicationUpStorage.yml
  doc/data/ttn-lw-cli.yml
Labels: documentation, release
