Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-07, with the labels that each got.

#421 doc: Add search breakpoint for small screens
  doc/themes/the-things-stack/assets/css/header/nav.scss
Labels: documentation, quickfix

#428 doc: v3.13.3 release docs
  doc/content/whats-new/3.13.3.md
  doc/data/api/ttn.lorawan.v3/enums.yml
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/api/ttn.lorawan.v3/services.yml
  doc/data/ttn-lw-cli.yml
Labels: documentation, release

#413 Document data retention/data privacy
  doc/archetypes/section-bundle/_index.md
  doc/content/reference/data-retention/_index.md
  doc/content/reference/data-retention/skip-encryption.png
Labels: documentation

#426 doc: Troubleshooting - extra reason for Token Exchange Refused
  doc/content/getting-started/installation/troubleshooting.md
Labels: documentation

#433 Improve webhook docs
  doc/content/integrations/webhooks/_index.md
  doc/content/integrations/webhooks/creating-webhooks.md
  doc/content/integrations/webhooks/webhook-templates/format.md
Labels: needs/triage

#422 Reorder getting started
  doc/content/getting-started/api/_index.md
  doc/content/getting-started/aws/_index.md
  doc/content/getting-started/cli/_index.md
  doc/content/getting-started/cloud-hosted/_index.md
  doc/content/getting-started/console/_index.md
  doc/content/getting-started/events/_index.md
  doc/content/getting-started/installation/_index.md
  doc/content/getting-started/migrating/_index.md
  doc/content/getting-started/troubleshooting/_index.md
  doc/content/getting-started/ttn/_index.md
  doc/content/getting-started/upgrading/_index.md
  doc/content/getting-started/user-management/_index.md
  doc/themes/the-things-stack/layouts/partials/pages-cards.html
Labels: documentation

#434 doc: Clarify type of uplink_message.rx_metadata.snr
  doc/content/reference/data-formats/_index.md
Labels: documentation

#436 doc: Add tenant ID to glossary
  doc/data/glossary.yml
Labels: documentation

#438 Remove remark on iot-shop.de
  doc/content/gateways/thethingsindoorgateway/_index.md
Labels: needs/triage

#437 adding document for cloudgate
  doc/content/gateways/cloudgate/BasicsStation-Config-Authentication.png
  doc/content/gateways/cloudgate/BasicsStation-Config-GatewayKey.png
  doc/content/gateways/cloudgate/BasicsStation-Config-ServerCACert.png
  doc/content/gateways/cloudgate/CloudGate.png
  doc/content/gateways/cloudgate/Connection-status.png
  doc/content/gateways/cloudgate/Create-API-Key.png
  doc/content/gateways/cloudgate/Insert-SIM.jpeg
  doc/content/gateways/cloudgate/Network-settings.png
  doc/content/gateways/cloudgate/Open-BasicsStation.png
  doc/content/gateways/cloudgate/_index.md
Labels: documentation

#432 doc: Update AWS IoT integration documentation with minor changes
  doc/content/integrations/cloud-integrations/aws-iot/default/create-cloudformation-stack.png
  doc/content/integrations/cloud-integrations/aws-iot/default/deployment-guide.md
  doc/content/integrations/cloud-integrations/aws-iot/default/messages.md
  doc/content/integrations/cloud-integrations/aws-iot/default/things-overview.png
  doc/content/integrations/cloud-integrations/aws-iot/default/things.md
Labels: documentation

#447 Document DevEui field in LBS downlinks
  doc/content/reference/lbs-implementation-guide/implementation-details.md
Labels: needs/triage

#442 Add missing API messages and enums (fix broken links)
  doc/content/reference/api/application.md
  doc/content/reference/api/application_pub_sub.md
  doc/content/reference/api/application_server.md
  doc/content/reference/api/application_webhooks.md
  doc/content/reference/api/end_device.md
  doc/content/reference/api/end_device_claiming.md
  doc/content/reference/api/events.md
  doc/content/reference/api/field-mask.md
  doc/content/reference/api/gateway.md
  doc/content/reference/api/gateway_server.md
  doc/content/reference/api/gateway_server_mqtt.md
  doc/content/reference/api/network_server.md
  doc/content/reference/api/organization.md
  doc/content/reference/api/storage_integration.md
  doc/content/reference/api/tenant.md
  doc/content/reference/api/user.md
  doc/content/reference/data-retention/_index.md
  doc/themes/the-things-stack/layouts/partials/proto/field-type.html
  doc/themes/the-things-stack/layouts/shortcodes/api-refs.html
  doc/themes/the-things-stack/layouts/shortcodes/proto/enum.html
  doc/themes/the-things-stack/layouts/shortcodes/proto/message.html
  doc/themes/the-things-stack/layouts/shortcodes/proto/method.html
Labels: documentation, needs/triage

#435 Add server addresses page
  doc/content/gateways/ciscowirelessgateway/_index.md
  doc/content/gateways/lora-basics-station/cups.md
  doc/content/gateways/lora-basics-station/lns.md
  doc/content/gateways/lorix-one/udp.md
  doc/content/gateways/mikrotik-knot/_index.md
  doc/content/gateways/mikrotik-ltap/_index.md
  doc/content/gateways/mikrotikrouterboard/_index.md
  doc/content/gateways/nasysoutdoorgateway/_index.md
  doc/content/gateways/tektelickonamicro/udp.md
  doc/content/gateways/thethingskickstartergateway/_index.md
  doc/content/gateways/troubleshooting/_index.md
  doc/content/gateways/ursalinkug8x/packet-forwarder.md
  doc/content/getting-started/console/login/_index.md
  doc/content/getting-started/quick-start/index.md
  doc/content/getting-started/server-addresses/_index.md
  doc/content/getting-started/upgrading/_index.md
  doc/content/getting-started/what-is-tts/_index.md
Labels: documentation

#451 Clarify license key format
  doc/content/reference/configuration/the-things-stack.md
Labels: documentation

#448 Improve installation guide
  doc/content/getting-started/installation/_index.md
  doc/content/getting-started/installation/configuration/index.md
  doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml
  doc/content/getting-started/installation/troubleshooting.md
Labels: documentation

#452 Document `ns.cluster-id` configuration option
  doc/content/reference/configuration/network-server.md
Labels: documentation

#450 doc: Add note in storage integration for The Things Stack Cloud (#30)
  doc/content/integrations/storage/_index.md
Labels: documentation

#429 doc: Update Ubidots integration to use Plugins
  doc/content/integrations/adding-integrations/_index.md
  doc/content/integrations/cloud-integrations/_index.md
  doc/content/integrations/cloud-integrations/ubidots/_index.md
  doc/content/integrations/cloud-integrations/ubidots/creating-function.png
  doc/content/integrations/cloud-integrations/ubidots/dashboard.png
  doc/content/integrations/cloud-integrations/ubidots/decoding-function.png
  doc/content/integrations/cloud-integrations/ubidots/device-type.png
  doc/content/integrations/cloud-integrations/ubidots/devices.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/LR1110-location.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/LR1110.jpg
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/_index.md
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/add-device.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/create-map-widget.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/device-owner.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/lora-cloud-das.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/lora-cloud-integration.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/manage-tokens.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/ubidots-device.png
  doc/content/integrations/cloud-integrations/ubidots/lora-edge-geolocation/ubidots-integration.png
  doc/content/integrations/cloud-integrations/ubidots/name-description.png
  doc/content/integrations/cloud-integrations/ubidots/plugin-id.png
  doc/content/integrations/cloud-integrations/ubidots/plugins.png
  doc/content/integrations/cloud-integrations/ubidots/running.png
  doc/content/integrations/cloud-integrations/ubidots/tokens.png
  doc/content/integrations/cloud-integrations/ubidots/tts-plugin.png
  doc/content/integrations/cloud-integrations/ubidots/ubidots-integration.png
  doc/content/integrations/cloud-integrations/ubidots/ubidots-webhook-creation.png
Labels: documentation

#459 Add some extra TTIG info
  doc/content/gateways/thethingsindoorgateway/TTIG_Serial.jpg
  doc/content/gateways/thethingsindoorgateway/_index.md
Labels: needs/triage

#461 doc: Add new API key right to create the AWS IoT Cloudformation stack
  doc/content/integrations/cloud-integrations/aws-iot/default/create-api-key.png
  doc/content/integrations/cloud-integrations/aws-iot/default/deployment-guide.md
Labels: needs/triage

#460 doc: Additions to LoRaWAN Best Practices
  doc/content/devices/best-practices/_index.md
Labels: documentation

#474 doc: Add purge reference
  doc/content/reference/purge/_index.md
Labels: documentation, status/blocked

#467 doc: Add Homey integration doc
  doc/content/integrations/cloud-integrations/homey/homey-template.png
  doc/content/integrations/cloud-integrations/homey/index.md
Labels: documentation

#466 doc: Add IoTinaBox guide
  doc/content/integrations/cloud-integrations/iotinabox/add-device.png
  doc/content/integrations/cloud-integrations/iotinabox/add-gateway.png
  doc/content/integrations/cloud-integrations/iotinabox/company.png
  doc/content/integrations/cloud-integrations/iotinabox/index.md
  doc/content/integrations/cloud-integrations/iotinabox/iotinabox-template.png
Labels: documentation

#464 Add Cayenne integration guide
  doc/content/integrations/cloud-integrations/cayenne/_index.md
  doc/content/integrations/cloud-integrations/cayenne/add-device.png
  doc/content/integrations/cloud-integrations/cayenne/cayenne-webhook-template.png
  doc/content/integrations/cloud-integrations/cayenne/choose-ttn-device.png
  doc/content/integrations/cloud-integrations/cayenne/device-overview.png
  doc/content/integrations/cloud-integrations/cayenne/monitor-data.png
  doc/content/integrations/cloud-integrations/cayenne/start-screen.png
Labels: documentation

#465 doc: Add Cloud Studio integration guide
  doc/content/integrations/cloud-integrations/cloudstudio/access-token.png
  doc/content/integrations/cloud-integrations/cloudstudio/add-device.png
  doc/content/integrations/cloud-integrations/cloudstudio/cloud-studio-template.png
  doc/content/integrations/cloud-integrations/cloudstudio/copy-token.png
  doc/content/integrations/cloud-integrations/cloudstudio/dashboard.png
  doc/content/integrations/cloud-integrations/cloudstudio/index.md
Labels: documentation

#485 doc: Add CLI troubleshooting
  doc/content/getting-started/cli/_index.md
  doc/content/reference/cli/troubleshooting.md
  doc/content/reference/stripe/_index.md
Labels: documentation

#472 doc: Add AWS IP note
  doc/content/getting-started/cloud-hosted/addresses.md
Labels: documentation

#476 doc: Add TTOG
  doc/content/gateways/thethingsoutdoor/GUI.png
  doc/content/gateways/thethingsoutdoor/TTOG.png
  doc/content/gateways/thethingsoutdoor/TTOG2.png
  doc/content/gateways/thethingsoutdoor/TTOG3.png
  doc/content/gateways/thethingsoutdoor/_index.md
  doc/content/gateways/thethingsoutdoor/gateway-info.png
  doc/content/gateways/thethingsoutdoor/upgrade_1.png
Labels: documentation
