Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-01, with the labels that each got.

#184 Doc/inline shortcodes
  CONTRIBUTING.md
  doc/archetypes/section-bundle/_index.md
  doc/content/gateways/semtech-udp-packet-forwarder/_index.md
  doc/content/getting-started/aws/ecs/deployment/_index.md
  doc/content/getting-started/migrating/import-devices.md
  doc/content/integrations/aws-iot/default/architecture.md
  doc/content/reference/configuration/identity-server.md
Labels: documentation

#183 doc: Document admin rights
  doc/content/getting-started/user-management/_index.md
Labels: documentation

#179 doc: Add note that CUPS overrides LNS
  doc/content/gateways/lora-basics-station/cups.md
Labels: documentation, quickfix

#190 doc: Add what is TTS section
  doc/content/getting-started/what-is-tts/_index.md
Labels: documentation

#193 doc: Explain payload formatter types
  doc/content/integrations/payload-formatters/_index.md
  doc/content/integrations/payload-formatters/console.md
  doc/content/integrations/payload-formatters/create.md
  doc/content/integrations/payload-formatters/device-repo.md
  doc/content/integrations/payload-formatters/javascript.md
Labels: documentation

#189 util: Change message proto layout
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/layouts/shortcodes/proto/message.html
Labels: documentation

#191 doc: Document Rx1Delay v2 difference
  doc/content/getting-started/migrating/configure-mac-settings.md
  doc/content/getting-started/migrating/major-changes.md
Labels: documentation

#180 doc: Add network errors to troubleshooting
  doc/content/getting-started/troubleshooting/_index.md
Labels: documentation

#192 doc: Explain auto completion
  doc/content/getting-started/cli/installing-cli/_index.md
Labels: documentation

#195 doc: Add note that IS is eu1 only
  doc/content/getting-started/cloud-hosted/addresses.md
Labels: documentation

#196 doc: Update console branding instructions for cloud
  doc/content/reference/branding/_index.md
Labels: documentation

#185 Add TTL and FormatTTL to email templates
  doc/content/reference/email-templates/available.md
Labels: c/identity server

#194 doc: Fix a broken reference
  doc/content/getting-started/what-is-tts/_index.md
Labels: documentation

#176 doc: Document location usage
  doc/content/devices/adding-devices/_index.md
  doc/content/devices/adding-devices/device-location.png
  doc/content/gateways/adding-gateways/_index.md
  doc/content/gateways/adding-gateways/gateway-location.png
Labels: documentation

#201 doc: Document thethings.iO integration
  doc/content/integrations/cloud-integrations/thethingsio/_index.md
  doc/content/integrations/cloud-integrations/thethingsio/monitor-data/_index.md
  doc/content/integrations/cloud-integrations/thethingsio/monitor-data/api-calls.png
  doc/content/integrations/cloud-integrations/thethingsio/monitor-data/data-chart.png
  doc/content/integrations/cloud-integrations/thethingsio/thethingsio-setup/_index.md
  doc/content/integrations/cloud-integrations/thethingsio/thethingsio-setup/callback-url.png
  doc/content/integrations/cloud-integrations/thethingsio/thethingsio-setup/cloud-code-function.png
  doc/content/integrations/cloud-integrations/thethingsio/thethingsio-setup/create-new-iot-product.png
  doc/content/integrations/cloud-integrations/thethingsio/thethingsio-setup/modify-cloud-code-function.png
  doc/content/integrations/cloud-integrations/thethingsio/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/thethingsio/tts-setup/thethingsio-webhook-integration.png
Labels: documentation
