Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-06, with the labels that each got.

#361 doc: Add note for PowerShell
  doc/content/download.html
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/_index.md
Labels: documentation

#373 Rename log messages metric for v3.13.1
  doc/content/getting-started/aws/ecs/monitoring/_index.md
  doc/content/reference/telemetry/_index.md
Labels: documentation

#372 doc: Update device repo links
  doc/content/integrations/payload-formatters/device-repo.md
Labels: documentation

#377 doc: Update docs for v3.13.1 release
  doc/content/whats-new/3.13.1.md
Labels: documentation, release

#375 Add example gateway location uplink message metadata
  doc/content/reference/data-formats/_index.md
Labels: documentation

#380 Update Adding Devices doc for device repo
  doc/content/devices/adding-devices/_index.md
  doc/content/devices/adding-devices/application-overview.png
  doc/content/devices/adding-devices/basic-settings.png
  doc/content/devices/adding-devices/device-abp-created.png
  doc/content/devices/adding-devices/device-creation-1.png
  doc/content/devices/adding-devices/device-creation-abp.png
  doc/content/devices/adding-devices/device-creation-otaa.png
  doc/content/devices/adding-devices/device-otaa-created.png
  doc/content/devices/adding-devices/device-repo-settings.png
  doc/content/devices/adding-devices/device-repo.png
  doc/content/devices/adding-devices/join-settings.png
  doc/content/devices/adding-devices/manual-settings.png
  doc/content/devices/adding-devices/network-settings.png
  doc/content/devices/adding-devices/register-manually.png
Labels: documentation

#385 Update API doc styling
  doc/assets/css/common/global.scss
  doc/layouts/shortcodes/proto/enum.html
  doc/layouts/shortcodes/proto/message.html
  doc/layouts/shortcodes/proto/method.html
Labels: documentation, needs/triage

#382 Move inline shortcodes to next line
  CONTRIBUTING.md
  doc/archetypes/section-bundle/_index.md
  doc/assets/css/common/global.scss
  doc/assets/css/sidebar/sidebar.scss
  doc/content/getting-started/aws/ecs/deployment/_index.md
  doc/content/getting-started/installation/configuration/index.md
  doc/content/integrations/aws-iot/_index.md
  doc/content/reference/configuration/application-server.md
  doc/content/reference/configuration/console.md
  doc/content/reference/configuration/device-claiming-server.md
  doc/content/reference/configuration/identity-server.md
  doc/content/reference/configuration/network-server.md
  doc/content/reference/configuration/packet-broker-agent.md
  doc/content/reference/configuration/the-things-stack.md
  doc/content/reference/telemetry/_index.md
  doc/layouts/_default/list.html
  doc/layouts/_default/single.html
  doc/layouts/partials/deprecated-in-version.html
  doc/layouts/partials/new-in-version.html
  doc/layouts/partials/pages-cards.html
  doc/layouts/partials/removed-in-version.html
  doc/layouts/shortcodes/removed-in-version.html
Labels: documentation

#390 Restructure layout
  doc/assets/img/overview-clickable.svg
  doc/content/_index.html
  doc/content/_index.md
  doc/layouts/_default/baseof.html
  doc/layouts/_default/list.html
  doc/layouts/_default/single.html
  doc/layouts/index.html
  doc/layouts/partials/whats-new.html
  doc/layouts/whats-new/list.html
  doc/layouts/whats-new/single.html
Labels: documentation, needs/triage

#393 Move search to nav
  doc/assets/css/header/nav.scss
  doc/assets/css/header/search.scss
  doc/assets/css/theme.scss
  doc/layouts/_default/baseof.html
  doc/layouts/partials/header/nav.html
Labels: documentation, needs/triage

#394 doc: Set fixed width middle column
  doc/layouts/_default/list.html
  doc/layouts/_default/single.html
  doc/layouts/whats-new/list.html
  doc/layouts/whats-new/single.html
Labels: documentation, quickfix

#395 doc: Update fonts urls
  doc/assets/css/common/fonts.scss
  doc/layouts/partials/head/head.html
  doc/static/fonts/ITCAvantGardePro-Bold/ITCAvantGardePro-Bold.eot
  doc/static/fonts/ITCAvantGardePro-Bold/ITCAvantGardePro-Bold.otf
  doc/static/fonts/ITCAvantGardePro-Bold/ITCAvantGardePro-Bold.svg
  doc/static/fonts/ITCAvantGardePro-Bold/ITCAvantGardePro-Bold.ttf
  doc/static/fonts/ITCAvantGardePro-Bold/ITCAvantGardePro-Bold.woff
  doc/static/fonts/ITCAvantGardePro-Bold/ITCAvantGardePro-Bold.woff2
  doc/static/fonts/Inter/Inter-Black.otf
  doc/static/fonts/Inter/Inter-Black.woff
  doc/static/fonts/Inter/Inter-Black.woff2
  doc/static/fonts/Inter/Inter-BlackItalic.otf
  doc/static/fonts/Inter/Inter-BlackItalic.woff
  doc/static/fonts/Inter/Inter-BlackItalic.woff2
  doc/static/fonts/Inter/Inter-Bold.otf
  doc/static/fonts/Inter/Inter-Bold.woff
  doc/static/fonts/Inter/Inter-Bold.woff2
  doc/static/fonts/Inter/Inter-BoldItalic.otf
  doc/static/fonts/Inter/Inter-BoldItalic.woff
  doc/static/fonts/Inter/Inter-BoldItalic.woff2
  doc/static/fonts/Inter/Inter-Italic.otf
  doc/static/fonts/Inter/Inter-Italic.woff
  doc/static/fonts/Inter/Inter-Italic.woff2
  doc/static/fonts/Inter/Inter-Light.otf
  doc/static/fonts/Inter/Inter-Light.woff
  doc/static/fonts/Inter/Inter-Light.woff2
  doc/static/fonts/Inter/Inter-LightItalic.otf
  doc/static/fonts/Inter/Inter-LightItalic.woff
  doc/static/fonts/Inter/Inter-LightItalic.woff2
  doc/static/fonts/Inter/Inter-Medium.otf
  doc/static/fonts/Inter/Inter-Medium.woff
  doc/static/fonts/Inter/Inter-Medium.woff2
  doc/static/fonts/Inter/Inter-MediumItalic.otf
  doc/static/fonts/Inter/Inter-MediumItalic.woff
  doc/static/fonts/Inter/Inter-MediumItalic.woff2
  doc/static/fonts/Inter/Inter-Regular.otf
  doc/static/fonts/Inter/Inter-Regular.woff
  doc/static/fonts/Inter/Inter-Regular.woff2
  doc/static/fonts/Inter/Inter-SemiBold.otf
  doc/static/fonts/Inter/Inter-SemiBold.woff
  doc/static/fonts/Inter/Inter-SemiBold.woff2
  doc/static/fonts/Inter/Inter-SemiBoldItalic.otf
  doc/static/fonts/Inter/Inter-SemiBoldItalic.woff
  doc/static/fonts/Inter/Inter-SemiBoldItalic.woff2
Labels: documentation, quickfix

#396 Remove @kschiffer from Hugo codeowners
  CODEOWNERS
Labels: tooling

#397 doc: Fix link to Integrations with MQTT Clients.
  doc/content/integrations/adding-integrations/_index.md
Labels: needs/triage

#392 doc: Add note about scheduling downlinks
  doc/content/integrations/cloud-integrations/aws-iot/default/architecture.md
Labels: documentation

#403 doc: Update gateway troubleshooting
  doc/content/gateways/adding-gateways/troubleshooting.md
Labels: documentation

#402 Add a prerequisites section to the Multitech Conduit AEP gateways doc for supporting LBS
  doc/content/gateways/multitechconduit/lbs.md
Labels: documentation, needs/triage

#411 doc: Update documentation for v3.13.2 release
  doc/content/whats-new/3.13.2.md
  doc/data/api/tti.lorawan.v3/messages.yml
  doc/data/api/tti.lorawan.v3/services.yml
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/ttn-lw-cli.yml
Labels: documentation, release

#381 Activate tabs with anchor links
  doc/assets/js/theme.js
Labels: documentation

#405 Improve the LBS configuration of the Lorix-One gateway
  doc/content/gateways/lorix-one/lbs.md
  doc/content/gateways/lorix-one/lorix-one-lora-settings-bs-lns.png
  doc/content/gateways/lorix-one/lorix-one-lora-settings-bs.png
Labels: documentation

#412 doc: Remove empty sections from What's new in version files
  .github/ISSUE_TEMPLATE/release.md
  doc/content/whats-new/3.10.6.md
  doc/content/whats-new/3.10.7.md
  doc/content/whats-new/3.10.8.md
  doc/content/whats-new/3.11.0.md
  doc/content/whats-new/3.11.1.md
  doc/content/whats-new/3.11.2.md
  doc/content/whats-new/3.11.3.md
  doc/content/whats-new/3.12.2.md
  doc/content/whats-new/3.13.0.md
  doc/content/whats-new/3.13.1.md
Labels: documentation, needs/triage

#404 Improve LBS configuration guide of the Laird Sentrius RG1XX Gateway
  doc/content/gateways/laird-sentrius/cups-certificate-configuration.png
  doc/content/gateways/laird-sentrius/cups-server-configuration.png
  doc/content/gateways/laird-sentrius/lbs.md
  doc/content/gateways/laird-sentrius/lns-certificate-configuration.png
  doc/content/gateways/laird-sentrius/lns-server-configuration.png
Labels: documentation

#418 Add ADR implementation reference
  doc/content/reference/adr/_index.md
Labels: documentation, needs/triage

#417 Gateway troubleshooting additions
  doc/content/gateways/adding-gateways/_index.md
  doc/content/gateways/adding-gateways/troubleshooting.md
  doc/content/gateways/ciscowirelessgateway/_index.md
  doc/content/gateways/gateway-claiming/_index.md
  doc/content/gateways/lora-basics-station/troubleshooting.md
  doc/content/gateways/moko-mkgw2-lw/_index.md
  doc/content/gateways/rak-7240/pf.md
  doc/content/gateways/semtech-udp-packet-forwarder/troubleshooting.md
  doc/content/gateways/troubleshooting/_index.md
  doc/content/gateways/udp/_index.md
  doc/content/gateways/udp/conf.png
  doc/content/getting-started/migrating/gateway-migration.md
Labels: documentation, needs/triage

#408 doc: Add videos
  doc/content/devices/adding-devices/_index.md
  doc/content/gateways/adding-gateways/_index.md
  doc/content/getting-started/events/_index.md
  doc/content/getting-started/user-management/_index.md
  doc/content/getting-started/user-management/org/_index.md
  doc/content/getting-started/user-management/rights/_index.md
  doc/content/getting-started/user-management/user/_index.md
  doc/content/integrations/adding-applications/_index.md
  doc/content/integrations/payload-formatters/_index.md
  doc/content/integrations/webhooks/creating-webhooks.md
Labels: documentation

#349 Update ID constraints for shorter ID
  doc/content/reference/id-eui-constraints/index.md
Labels: documentation

#407 Improve LoRa Cloud integration docs
  doc/content/integrations/lora-cloud/_index.md
  doc/content/integrations/lora-cloud/add-device.png
  doc/content/integrations/lora-cloud/copy-primary-token.png
  doc/content/integrations/lora-cloud/copy-token.png
  doc/content/integrations/lora-cloud/das.md
  doc/content/integrations/lora-cloud/das.png
  doc/content/integrations/lora-cloud/full-info.png
  doc/content/integrations/lora-cloud/geolocation-integration.png
  doc/content/integrations/lora-cloud/geolocation-tokens.png
  doc/content/integrations/lora-cloud/geolocation.md
  doc/content/integrations/lora-cloud/geolocation.png
  doc/content/integrations/lora-cloud/get-info.png
  doc/content/integrations/lora-cloud/gnss-assisted-scan-result.png
  doc/content/integrations/lora-cloud/gnss.png
  doc/content/integrations/lora-cloud/paste-token.png
  doc/content/integrations/lora-cloud/send-requests.png
  doc/content/integrations/lora-cloud/toa-rssi.png
  doc/content/integrations/lora-cloud/toa-wifi.png
  doc/content/integrations/lora-cloud/token-creation.png
  doc/content/integrations/lora-cloud/wifi-scan-result.png
Labels: documentation

#424 TTIG claiming
  doc/content/gateways/thethingsindoorgateway/TTIG.jpeg
  doc/content/gateways/thethingsindoorgateway/TTIG_Claim.png
  doc/content/gateways/thethingsindoorgateway/TTIG_EUI.png
  doc/content/gateways/thethingsindoorgateway/TTIG_WiFi_Setup.png
  doc/content/gateways/thethingsindoorgateway/_index.md
  doc/layouts/shortcodes/ttig.html
Labels: c/device claiming, c/gateway server

#386 doc: Document V3 -> V2 routing, reusing payload (de)coders, TTIG migration
  doc/content/getting-started/migrating/gateway-migration.md
  doc/content/getting-started/migrating/migrating-from-v2/_index.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-console.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/establish-new-session.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session.md
  doc/content/getting-started/migrating/migrating-from-v2/packet-broker-requirements.md
Labels: documentation

#425 Add Claim Authentication Code Mismatch to TTIG FAQ
  doc/content/gateways/thethingsindoorgateway/_index.md
Labels: needs/triage
