Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-02, with the labels that each got.

#197 Add instructions to update CLI
  doc/content/gateways/lora-basics-station/cups.md
  doc/content/getting-started/cli/installing-cli/_index.md
  doc/content/integrations/storage/configuration.md
  doc/content/integrations/storage/enable.md
  doc/content/integrations/storage/retrieve.md
Labels: documentation

#206 doc: Document Qubitro integration
  doc/content/integrations/cloud-integrations/qubitro/_index.md
  doc/content/integrations/cloud-integrations/qubitro/monitor-data/_index.md
  doc/content/integrations/cloud-integrations/qubitro/monitor-data/create-a-chart.png
  doc/content/integrations/cloud-integrations/qubitro/monitor-data/decoded-data.png
  doc/content/integrations/cloud-integrations/qubitro/monitor-data/real-time-graph.png
  doc/content/integrations/cloud-integrations/qubitro/qubitro-setup/_index.md
  doc/content/integrations/cloud-integrations/qubitro/qubitro-setup/create-new-project.png
  doc/content/integrations/cloud-integrations/qubitro/qubitro-setup/project-settings.png
  doc/content/integrations/cloud-integrations/qubitro/qubitro-setup/webhook-signing-key.png
  doc/content/integrations/cloud-integrations/qubitro/tts-setup/_index.md
  doc/content/integrations/cloud-integrations/qubitro/tts-setup/creating-a-webhook.png
Labels: documentation

#216 Fix broken svg link
  doc/content/_index.html
  doc/layouts/shortcodes/rel-url.html
  doc/themes/the-things-stack/yarn.lock
Labels: documentation

#130 Document using ttn-lw-migrate to migrate from v2
  doc/content/getting-started/migrating/_index.md
  doc/content/getting-started/migrating/device-json.md
  doc/content/getting-started/migrating/gateway-migration.md
  doc/content/getting-started/migrating/major-changes.md
  doc/content/getting-started/migrating/migrate-from-chirpstack.md
  doc/content/getting-started/migrating/migrating-from-v2.md
Labels: documentation, prio/medium

#217 doc: Update thethings.io guide
  doc/content/integrations/cloud-integrations/thethingsio/thethingsio-setup/_index.md
  doc/content/integrations/cloud-integrations/thethingsio/thethingsio-setup/callback-url.png
  doc/content/integrations/cloud-integrations/thethingsio/tts-setup/_index.md
Labels: documentation

#134 Create distribution badges to mark features specific to a distribution
  .editorconfig
  CONTRIBUTING.md
  Makefile
  doc/archetypes/section-bundle/_index.md
  doc/content/download.html
  doc/content/getting-started/aws/ami/_index.md
  doc/content/getting-started/installation/_index.md
  doc/content/integrations/aws-iot/_index.md
  doc/content/integrations/aws-iot/application-server-telemetry/_index.md
  doc/content/integrations/storage/_index.md
  doc/content/reference/configuration/application-server.md
  doc/data/distributions.yml
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/layouts/_default/list.html
  doc/themes/the-things-stack/layouts/_default/single.html
  doc/themes/the-things-stack/layouts/partials/distribution-icons.html
  doc/themes/the-things-stack/layouts/partials/distributions.html
  doc/themes/the-things-stack/layouts/partials/pages-cards.html
  doc/themes/the-things-stack/layouts/shortcodes/distributions-inline.html
  doc/themes/the-things-stack/layouts/shortcodes/distributions-list.html
  doc/themes/the-things-stack/package-lock.json
  doc/themes/the-things-stack/package.json
  doc/themes/the-things-stack/static/img/tts_frames/frame_aws.svg
  doc/themes/the-things-stack/static/img/tts_frames/frame_cloud.svg
  doc/themes/the-things-stack/static/img/tts_frames/frame_dedicated_cloud.svg
  doc/themes/the-things-stack/static/img/tts_frames/frame_enterprise.svg
  doc/themes/the-things-stack/static/img/tts_frames/frame_open_source.svg
  doc/themes/the-things-stack/static/img/tts_frames/frame_ttn.svg
  doc/themes/the-things-stack/yarn.lock
Labels: documentation

#221 Improve Storage Integration API documentation
  doc/content/integrations/storage/retrieve.md
Labels: documentation

#225 doc: Fix broken open source link
  doc/content/download.html
Labels: documentation, quickfix

#226 doc: Remove duplicate custom certs section
  doc/content/getting-started/installation/certificates.md
Labels: documentation, quickfix

#205 Update variables and functions in email templates
  doc/content/reference/email-templates/available.md
Labels: c/identity server, documentation

#204 Add reference for is.user-registration.enabled config option
  doc/content/reference/configuration/identity-server.md
Labels: c/identity server, documentation

#229 doc: Update to 3.11
  doc/config/_default/config.toml
Labels: documentation

#220 doc: Add ABP vs OTAA doc
  doc/content/devices/abp-vs-otaa/_index.md
Labels: documentation

#231 doc: Update download page
  doc/content/download.html
Labels: documentation

#228 util: Replace distributions-inline with distributions shortcode
  CONTRIBUTING.md
  doc/archetypes/section-bundle/_index.md
  doc/content/getting-started/installation/configuration/_index.md
  doc/content/getting-started/migrating/migrating-from-v2.md
  doc/content/integrations/aws-iot/default/deployment-guide.md
  doc/content/reference/branding/_index.md
  doc/content/reference/configuration/console.md
  doc/content/reference/configuration/identity-server.md
  doc/content/reference/configuration/network-server.md
  doc/content/reference/configuration/the-things-stack.md
  doc/content/reference/email-templates/available.md
  doc/content/reference/networking/_index.md
  doc/content/reference/telemetry/_index.md
  doc/themes/the-things-stack/layouts/shortcodes/distributions-inline.html
Labels: documentation, quickfix

#219 doc: Add troubleshooting for UDP packet forwarder and devices
  doc/content/devices/adding-devices/troubleshooting.md
  doc/content/gateways/semtech-udp-packet-forwarder/_index.md
  doc/content/gateways/semtech-udp-packet-forwarder/troubleshooting.md
Labels: documentation

#239 Document the ns-db,as-db,dcs-db commands
  doc/content/getting-started/aws/ecs/database-operations/_index.md
Labels: c/application server, c/network server

#233 Add release template
  .github/ISSUE_TEMPLATE/release.md
Labels: documentation

#241 util: Enable docs sitemap
  doc/config/_default/config.toml
Labels: documentation
