Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-09, with the labels that each got.

#551 doc: Add timescaledb config options
  doc/content/integrations/storage/configuration.md
Labels: documentation

#387 doc: Change table layout
  doc/archetypes/section-bundle/_index.md
  doc/content/getting-started/migrating/device-json.md
  doc/themes/the-things-stack/assets/css/common/global.scss
Labels: documentation

#554 doc: Add a note about already registered in other tenant
  doc/content/gateways/troubleshooting/_index.md
Labels: documentation

#550 doc: Add console instructions for pb
  doc/content/getting-started/packet-broker/configure/_index.md
  doc/content/getting-started/packet-broker/configure/default-policy.png
  doc/content/getting-started/packet-broker/configure/pb-config.png
  doc/content/getting-started/packet-broker/configure/pb-custom.png
  doc/content/getting-started/packet-broker/configure/pb-menu.png
  doc/content/getting-started/packet-broker/configure/pb-networks.png
  doc/content/getting-started/packet-broker/configure/pb-public.png
  doc/content/getting-started/packet-broker/configure/pb-register.png
  doc/content/getting-started/packet-broker/configure/registration.md
  doc/content/getting-started/packet-broker/configure/routing-policies.md
  doc/content/getting-started/packet-broker/connect.md
Labels: documentation

#560 Fix broken packet broker reference
  doc/content/reference/pb-routing/_index.md
Labels: documentation, quickfix

#559 doc: Add Kickstarter FAQ
  doc/content/gateways/thethingskickstartergateway/_index.md
  doc/content/gateways/thethingskickstartergateway/screen-macos.png
  doc/content/gateways/thethingskickstartergateway/uart-sample.jpg
Labels: documentation

#553 doc: Note about using API key
  doc/content/reference/api/authentication.md
Labels: documentation

#563 doc: Add gateway location troubleshooting
  doc/content/gateways/troubleshooting/_index.md
Labels: documentation

#568 Document Gateway RTT
  doc/content/reference/gateway-rtt/_index.md
Labels: documentation

#572 doc: Add v3.15.0 release docs
  doc/config/_default/config.toml
  doc/content/reference/api/tenant.md
  doc/content/whats-new/3.15.0.md
  doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.UserLogin.yml
  doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.yml
  doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.JoinServer.yml
  doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.yml
  doc/data/api/tti.lorawan.v3/messages/Configuration.yml
  doc/data/api/ttn.lorawan.v3/messages/Gateway.yml
  doc/data/api/ttn.lorawan.v3/messages/GetPhyVersionsRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/GetPhyVersionsResponse.VersionInfo.yml
  doc/data/api/ttn.lorawan.v3/messages/GetPhyVersionsResponse.yml
  doc/data/api/ttn.lorawan.v3/messages/IsConfiguration.UserLogin.yml
  doc/data/api/ttn.lorawan.v3/messages/IsConfiguration.yml
  doc/data/api/ttn.lorawan.v3/services/Configuration.yml
  doc/data/ttn-lw-cli.yml
Labels: documentation, release

#573 Migration FAQ doc
  doc/content/getting-started/migrating/faq.md
Labels: documentation

#558 doc: Update device import doc
  doc/content/getting-started/migrating/import-devices.md
  doc/content/getting-started/migrating/import-end-devices.png
  doc/content/getting-started/migrating/operation-finished.png
  doc/content/getting-started/migrating/successful-import.png
  doc/content/getting-started/migrating/upload-file.png
Labels: documentation

#582 doc: Add device registration troubleshooting
  doc/content/devices/troubleshooting/_index.md
Labels: documentation

#581 doc: Add status page refs for Cloud Hosted and Packet Broker
  doc/content/getting-started/cloud-hosted/_index.md
  doc/content/getting-started/packet-broker/_index.md
Labels: documentation

#590 doc: Add note about using all zeros JoinEUI
  doc/content/devices/adding-devices/_index.md
Labels: documentation

#589 doc: Fix migration tool flag-related notes
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/establish-new-session.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session.md
Labels: documentation
