Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-04, with the labels that each got.

#294 Release 3.11.3
  .github/ISSUE_TEMPLATE/release.md
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/api/ttn.lorawan.v3/services.yml
  doc/data/ttn-lw-cli.yml
Labels: documentation

#178 doc: Add MikroTik LtAP gateway
  doc/content/gateways/mikrotik-ltap/LtaP.jpg
  doc/content/gateways/mikrotik-ltap/_index.md
  doc/content/gateways/mikrotik-ltap/parameters.png
  doc/content/gateways/mikrotik-ltap/portal-lora-disable.png
  doc/content/gateways/mikrotik-ltap/portal-lora.png
  doc/content/gateways/mikrotik-ltap/portal.png
  doc/content/gateways/mikrotik-ltap/servers.png
Labels: documentation

#297 doc: Update troubleshooting
  doc/content/getting-started/installation/troubleshooting.md
Labels: documentation

#301 Add note about dev_id constraints in TTS V3
  doc/content/getting-started/migrating/migrating-from-v2.md
Labels: documentation

#290 Rate Limiting documentation reference
  doc/content/reference/configuration/the-things-stack.md
  doc/content/reference/rate-limiting/_index.md
  doc/data/rate-limiting.yml
  doc/layouts/shortcodes/rate-limiting.html
Labels: c/shared

#303 doc: Update data for v3.12.0 release
  .github/ISSUE_TEMPLATE/release.md
  doc/config/_default/config.toml
  doc/content/reference/api/application.md
  doc/content/reference/api/gateway.md
  doc/content/reference/api/organization.md
  doc/content/reference/api/user.md
  doc/data/api/tti.lorawan.v3/messages.yml
  doc/data/api/tti.lorawan.v3/services.yml
  doc/data/api/ttn.lorawan.v3/enums.yml
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/api/ttn.lorawan.v3/services.yml
  doc/data/ttn-lw-cli.yml
Labels: release

#202 doc: Add whats-new
  .github/ISSUE_TEMPLATE/release.md
  doc/assets/css/common/global.scss
  doc/content/_index.html
  doc/content/whats-new/3.10.0.md
  doc/content/whats-new/3.10.1.md
  doc/content/whats-new/3.10.2.md
  doc/content/whats-new/3.10.3.md
  doc/content/whats-new/3.10.4.md
  doc/content/whats-new/3.10.5.md
  doc/content/whats-new/3.10.6.md
  doc/content/whats-new/3.10.7.md
  doc/content/whats-new/3.10.8.md
  doc/content/whats-new/3.11.0.md
  doc/content/whats-new/3.11.1.md
  doc/content/whats-new/3.11.2.md
  doc/content/whats-new/3.11.3.md
  doc/content/whats-new/3.12.0.md
  doc/content/whats-new/3.12.1.md
  doc/content/whats-new/_index.md
  doc/layouts/partials/whats-new-cards.html
  doc/layouts/shortcodes/whats-new.html
  doc/layouts/whats-new/list.html
  doc/layouts/whats-new/single.html
Labels: documentation

#299 doc: Add quick start
  doc/content/getting-started/quick-start/index.md
Labels: documentation

#312 Update for v3.12.1 release
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/ttn-lw-cli.yml
Labels: release

#311 doc: Remove old new-in-version tags, small fixes
  doc/content/gateways/semtech-udp-packet-forwarder/_index.md
  doc/content/getting-started/aws/ecs/deployment/_index.md
  doc/content/getting-started/migrating/import-devices.md
  doc/content/integrations/adding-applications/_index.md
  doc/content/integrations/aws-iot/default/architecture.md
  doc/content/integrations/aws-iot/default/deployment-guide.md
  doc/content/integrations/pubsub/_index.md
  doc/content/integrations/storage/_index.md
  doc/content/integrations/storage/enable.md
  doc/content/integrations/webhooks/webhook-templates/format.md
  doc/content/reference/components/application-server.md
  doc/content/reference/configuration/application-server.md
  doc/content/reference/configuration/identity-server.md
  doc/content/reference/configuration/the-things-stack.md
  doc/content/reference/federated-auth/_index.md
Labels: documentation

#305 Update migration docs
  doc/content/getting-started/migrating/_index.md
  doc/content/getting-started/migrating/configure-mac-settings.md
  doc/content/getting-started/migrating/device-json.md
  doc/content/getting-started/migrating/gateway-migration.md
  doc/content/getting-started/migrating/import-devices.md
  doc/content/getting-started/migrating/major-changes.md
  doc/content/getting-started/migrating/migrate-from-chirpstack.md
  doc/content/getting-started/migrating/migrating-from-v2.md
  doc/content/getting-started/migrating/migrating-from-v2/_index.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-console.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/_index.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/establish-new-session.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session.md
  doc/content/getting-started/migrating/migrating-from-v2/packet-broker-requirements.md
  doc/layouts/shortcodes/ttnv2.html
Labels: documentation

#313 doc: Fix content overflow
  doc/assets/css/sidebar/sidebar.scss
Labels: documentation

#317 Issue/installing migration tool
  doc/content/getting-started/migrating/migrate-from-chirpstack.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-console.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/_index.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/establish-new-session.md
  doc/content/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session.md
  doc/content/getting-started/migrating/migrating-from-v2/packet-broker-requirements.md
  doc/content/getting-started/migrating/migration-tool.md
  go.sum
Labels: documentation

#326 Rename LR1110 to LoRa Edge™
  doc/content/integrations/adding-integrations/_index.md
  doc/content/integrations/lora-edge-geolocation/LR1110-location.png
  doc/content/integrations/lora-edge-geolocation/LR1110.jpg
  doc/content/integrations/lora-edge-geolocation/_index.md
  doc/content/integrations/lora-edge-geolocation/add-device.png
  doc/content/integrations/lora-edge-geolocation/create-map-widget.png
  doc/content/integrations/lora-edge-geolocation/device-owner.png
  doc/content/integrations/lora-edge-geolocation/lora-cloud-das.png
  doc/content/integrations/lora-edge-geolocation/lora-cloud-integration.png
  doc/content/integrations/lora-edge-geolocation/manage-tokens.png
  doc/content/integrations/lora-edge-geolocation/ubidots-device.png
  doc/content/integrations/lora-edge-geolocation/ubidots-integration.png
Labels: quickfix

#323 doc: Fix typo
  doc/content/getting-started/console/_index.md
Labels: documentation, quickfix

#322 Fix headers and add anchor links
  doc/assets/css/common/global.scss
  doc/layouts/_default/list.html
  doc/layouts/_default/single.html
  doc/layouts/partials/header-hash.html
  doc/layouts/partials/sidebar/headers.html
Labels: documentation

#332 doc: Update data for v3.12.2 release
  doc/content/whats-new/3.12.2.md
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/api/ttn.lorawan.v3/services.yml
  doc/data/ttn-lw-cli.yml
Labels: documentation, release
