Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-05, with the labels that each got.

#289 Add troubleshooting cases for join issue
  doc/content/devices/troubleshooting/_index.md
Labels: documentation

#329 Update hash css
  doc/assets/css/common/global.scss
Labels: documentation

#328 Add API examples for downlink with payload encoder
  doc/content/getting-started/api/_index.md
  doc/content/integrations/webhooks/scheduling-downlinks.md
Labels: documentation

#324 Replace Lato with Inter font
  doc/assets/css/common/fonts.scss
  doc/static/fonts/Inter-Bold.woff
  doc/static/fonts/Inter-Regular.woff
  doc/static/fonts/Lato-Bold.eot
  doc/static/fonts/Lato-Bold.ttf
  doc/static/fonts/Lato-Bold.woff
  doc/static/fonts/Lato-Bold.woff2
  doc/static/fonts/Lato-Regular.eot
  doc/static/fonts/Lato-Regular.ttf
  doc/static/fonts/Lato-Regular.woff
  doc/static/fonts/Lato-Regular.woff2
Labels: documentation

#300 Fix anchor link navbar offset
  doc/assets/css/common/variables.scss
  doc/assets/css/header/nav.scss
Labels: bug

#335 util: Fix broken downloads link
  doc/layouts/partials/distribution-icons.html
Labels: documentation

#327 doc: Add mokosmart gateway
  doc/content/gateways/moko-mkgw2-lw/_index.md
  doc/content/gateways/moko-mkgw2-lw/eui.png
  doc/content/gateways/moko-mkgw2-lw/login-web.png
  doc/content/gateways/moko-mkgw2-lw/mkgw2-lw.jpg
Labels: documentation

#333 doc: Updating the release template
  .github/ISSUE_TEMPLATE/release.md
Labels: documentation

#337 Fix typo in nasysoutdoorgateway
  doc/content/gateways/nasysoutdoorgateway/_index.md
Labels: documentation, quickfix

#321 doc: Add Mikrotik KNOT documentation
  doc/content/gateways/mikrotik-knot/KNOT-antenna.png
  doc/content/gateways/mikrotik-knot/_index.md
  doc/content/gateways/mikrotik-knot/lte-m-check.png
  doc/content/gateways/mikrotik-knot/mikrotik-knot.jpeg
  doc/content/gateways/mikrotik-knot/parameters.png
  doc/content/gateways/mikrotik-knot/portal-lora-disable.png
  doc/content/gateways/mikrotik-knot/portal-lora.png
  doc/content/gateways/mikrotik-knot/portal.png
  doc/content/gateways/mikrotik-knot/servers.png
Labels: documentation

#339 Document Packet Broker regional cluster config
  doc/content/reference/packet-broker/_index.md
  doc/content/reference/packet-broker/connect.md
  doc/data/distributions.yml
  doc/layouts/partials/distribution-icons.html
  doc/layouts/partials/distributions.html
  doc/layouts/shortcodes/distributions-inline.html
  doc/layouts/shortcodes/distributions-list.html
Labels: documentation

#338 doc: Add instructions for console LNS API key
  doc/content/gateways/lora-basics-station/cups-rights.png
  doc/content/gateways/lora-basics-station/cups.md
  doc/content/gateways/lora-basics-station/lns-key.png
  doc/content/gateways/lora-basics-station/lns-rights.png
  doc/content/gateways/lora-basics-station/lns.md
Labels: documentation

#341 doc: Add migration decision tree
  doc/content/getting-started/migrating/migrating-from-v2/_index.md
  doc/content/getting-started/migrating/migrating-from-v2/migration-decision-tree.jpg
Labels: documentation

#346 Add documentation for new deployment information configs
  doc/content/reference/branding/_index.md
  doc/content/reference/configuration/console.md
  doc/content/reference/configuration/identity-server.md
Labels: documentation

#350 Change anchor hashes to JS
  doc/assets/css/common/global.scss
  doc/assets/css/header/nav.scss
  doc/assets/js/theme.js
  doc/layouts/_default/list.html
  doc/layouts/_default/single.html
  doc/layouts/partials/header-hash.html
Labels: documentation

#351 doc: Remove comments from ca.pem
  .editorconfig
  doc/content/reference/root-certificates/ca.pem
Labels: documentation

#345 Installation & configuration instructions for tti-lw-cli
  doc/content/getting-started/cli/installing-cli/_index.md
  doc/content/getting-started/cli/login/_index.md
Labels: documentation

#355 Fix example configuration
  doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-enterprise.yml
  doc/content/getting-started/installation/configuration/ttn-lw-stack-docker-open-source.yml
Labels: quickfix

#360 doc: Release docs v3.13.0
  doc/config/_default/config.toml
  doc/content/whats-new/3.13.0.md
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/api/ttn.lorawan.v3/services.yml
  doc/data/ttn-lw-cli.yml
Labels: documentation, release

#366 doc: UIB integration guide
  doc/content/integrations/cloud-integrations/uib/_index.md
  doc/content/integrations/cloud-integrations/uib/uib-template-webhook.png
Labels: documentation

#367 Email change in documentation
  doc/content/integrations/cloud-integrations/uib/_index.md
Labels: needs/triage

#370 doc: Remove migration banner
  doc/assets/css/header/nav.scss
  doc/assets/js/theme.js
  doc/layouts/partials/header/nav.html
Labels: needs/triage
