Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2021-03, with the labels that each got.

#238 Document ID and EUI constraints
  doc/content/integrations/aws-iot/default/things.md
  doc/content/reference/id-eui-constraints/index.md
Labels: documentation

#243 Explain creating vs claiming device in AWS IoT
  doc/content/integrations/aws-iot/default/things.md
Labels: documentation

#250 Improve installation guide
  doc/content/getting-started/installation/certificates.md
  doc/content/getting-started/installation/configuration/_index.md
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/assets/css/vendor/bulma-tooltip.min.css
  doc/themes/the-things-stack/package.json
  doc/themes/the-things-stack/yarn.lock
Labels: documentation

#245 Add sections for supported classes, LoRaWAN specifications, and Regional Parameters
  doc/content/devices/class-b/index.md
  doc/content/devices/class-c/_index.md
  doc/content/devices/multicast/index.md
  doc/content/reference/spec-regional-parameters/index.md
Labels: documentation

#254 Update data for v3.11.2 release
  doc/data/api/ttn.lorawan.v3/messages.yml
  doc/data/api/ttn.lorawan.v3/services.yml
  doc/data/ttn-lw-cli.yml
Labels: release

#203 doc: Add instruction for Rx1 on migrated devices
  doc/content/getting-started/migrating/device-json.md
Labels: documentation

#255 doc: Search layout quickfix
  doc/assets/css/header/search.scss
Labels: documentation, quickfix

#257 doc: Add banner html padding
  doc/assets/css/common/variables.scss
  doc/assets/css/header/nav.scss
  doc/assets/js/theme.js
Labels: documentation

#256 Add note about peering on TTS cloud
  doc/content/reference/packet-broker/enable.md
Labels: documentation

#260 Add PBA telemetry descriptions
  doc/content/getting-started/aws/ecs/monitoring/_index.md
  doc/content/reference/telemetry/_index.md
Labels: c/packet broker agent

#263 Doc/update migration doc
  doc/content/getting-started/migrating/migrating-from-v2.md
Labels: documentation

#251 Add GCS deployment description
  doc/content/getting-started/aws/ecs/deployment/_index.md
Labels: documentation

#276 Update aws integration end-to-end-encryption section
  doc/content/integrations/aws-iot/default/architecture.md
  doc/content/integrations/aws-iot/default/deployment-guide.md
Labels: documentation

#279 Make container wider
  doc/assets/css/common/variables.scss
  doc/assets/css/sidebar/sidebar.scss
  doc/content/getting-started/installation/configuration/index.md
  doc/layouts/_default/baseof.html
Labels: ui/web

#269 doc: Add CLI note about au1 IS
  doc/content/getting-started/cli/installing-cli/_index.md
Labels: documentation

#283 Doc/document rak 7240 gw
  doc/content/gateways/rak-7240/_index.md
  doc/content/gateways/rak-7240/bs.md
  doc/content/gateways/rak-7240/cellular-interface.jpg
  doc/content/gateways/rak-7240/cups-lns.jpg
  doc/content/gateways/rak-7240/ethernet-poe.png
  doc/content/gateways/rak-7240/pf.md
  doc/content/gateways/rak-7240/rak7240.jpg
  doc/content/gateways/rak-7240/udp-pf.jpg
  doc/content/gateways/rak-7240/wireless-client.png
  doc/content/gateways/rak-7240/wmp.jpg
Labels: documentation

#282 doc: Note about gateway ID inconsistency
  doc/content/gateways/semtech-udp-packet-forwarder/_index.md
Labels: documentation

#296 Document changes in MAC command handling from V2
  doc/content/getting-started/migrating/major-changes.md
Labels: c/network server

#288 Adding notes for using MQTT Server in a multi-tenant environment
  doc/content/integrations/mqtt-clients/eclipse-mosquitto/_index.md
  doc/content/integrations/mqtt-clients/eclipse-paho/_index.md
  doc/content/integrations/mqtt-clients/hivemq/_index.md
  doc/content/integrations/mqtt-clients/mqttbox/_index.md
  doc/content/integrations/mqtt/_index.md
  doc/content/integrations/mqtt/cloud-hosted.md
Labels: documentation
