Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2022-04, with the labels that each got.

#838 Add ECS Changelog
  .github/ISSUE_TEMPLATE/release.md
  doc/content/getting-started/aws/ecs/changelog/index.md
Labels: documentation

#842 Update Hugo to 0.96 and Go to 1.18
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  doc/.hugo_build.lock
  go.mod
  go.sum
  tools.go
Labels: dependencies, technical debt

#850 Use name The Things Stack Enterprise
  doc/content/getting-started/aws/ami/deployment-guide/_index.md
  doc/content/getting-started/aws/ami/post-deployment/_index.md
  doc/content/getting-started/aws/ami/updating/_index.md
  doc/content/getting-started/aws/ecs/monitoring/_index.md
  doc/content/getting-started/cloud-hosted/_index.md
Labels: technical debt

#848 doc: Add RP002 info, modify specification names
  doc/content/reference/spec-regional-parameters/index.md
Labels: documentation

#847 doc: Link to tenant settings -> branding options
  doc/content/reference/branding/_index.md
Labels: documentation

#854 doc: Improve QR and claiming docs
  doc/content/devices/device-claiming/claim-devices.md
  doc/content/devices/device-claiming/make-device-claimable.md
  doc/content/devices/generate-qr-code/_index.md
Labels: documentation
