Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2022-06, with the labels that each got.

#884 doc: Add Browan Minihub Pro doc
  doc/content/gateways/browan-minihub-pro/_index.md
  doc/content/gateways/browan-minihub-pro/minihub-pro.png
  doc/content/gateways/rak-7240/_index.md
Labels: documentation

#894 Add shell flag to CLI completion command examples
  doc/content/ttn-lw-cli/ttn-lw-cli_completion_bash.md
  doc/content/ttn-lw-cli/ttn-lw-cli_completion_fish.md
  doc/content/ttn-lw-cli/ttn-lw-cli_completion_powershell.md
  doc/content/ttn-lw-cli/ttn-lw-cli_completion_zsh.md
Labels: ui/cli

#892 doc: Add v3.19.2 release docs
  doc/config/_default/config.toml
  doc/content/getting-started/aws/ecs/changelog/index.md
  doc/content/reference/api/network_operations_center.md
  doc/content/reference/api/tenant.md
  doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_create.md
  doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get-default-mac-settings.md
  doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_get.md
  doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_reset.md
  doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_search.md
  doc/content/ttn-lw-cli/ttn-lw-cli_end-devices_set.md
  doc/content/ttn-lw-cli/ttn-lw-cli_templates_create.md
  doc/content/ttn-lw-cli/ttn-lw-cli_templates_execute.md
  doc/content/ttn-lw-cli/ttn-lw-cli_templates_extend.md
  doc/content/ttn-lw-cli/ttn-lw-cli_tenants_create.md
  doc/content/ttn-lw-cli/ttn-lw-cli_tenants_get.md
  doc/content/ttn-lw-cli/ttn-lw-cli_tenants_list.md
  doc/content/ttn-lw-cli/ttn-lw-cli_tenants_search.md
  doc/content/ttn-lw-cli/ttn-lw-cli_tenants_update.md
  doc/content/whats-new/3.19.2.md
  doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.Email.Network.yml
  doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.Email.yml
  doc/data/api/tti.lorawan.v3/messages/Configuration.Cluster.IdentityServer.yml
  doc/data/api/tti.lorawan.v3/messages/GatewaysConnectedResponse.yml
  doc/data/api/tti.lorawan.v3/messages/GatewaysConnectedTimeBucket.yml
  doc/data/api/tti.lorawan.v3/messages/GetTenantIdentifiersForEndDeviceEUIsRequest.yml
  doc/data/api/tti.lorawan.v3/messages/GetTenantIdentifiersForGatewayEUIRequest.yml
  doc/data/api/tti.lorawan.v3/messages/TimeBucketRequest.yml
  doc/data/api/tti.lorawan.v3/services/Noc.yml
  doc/data/api/ttn.lorawan.v3/enums/ClusterRole.yml
  doc/data/api/ttn.lorawan.v3/messages/ApplicationActivationSettings.yml
  doc/data/api/ttn.lorawan.v3/messages/ClaimEndDeviceRequest.AuthenticatedIdentifiers.yml
  doc/data/api/ttn.lorawan.v3/messages/ClaimEndDeviceRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/ClaimGatewayRequest.AuthenticatedIdentifiers.yml
  doc/data/api/ttn.lorawan.v3/messages/DeriveSessionKeysRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/EntityStateChangedNotification.yml
  doc/data/api/ttn.lorawan.v3/messages/GetClaimStatusResponse.yml
  doc/data/api/ttn.lorawan.v3/messages/GetDefaultJoinEUIResponse.yml
  doc/data/api/ttn.lorawan.v3/messages/GetGatewayIdentifiersForEUIRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/GetInfoByJoinEUIRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/GetInfoByJoinEUIResponse.yml
  doc/data/api/ttn.lorawan.v3/messages/IssueDevEUIResponse.yml
  doc/data/api/ttn.lorawan.v3/messages/JoinAcceptMICRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/JoinEUIPrefix.yml
  doc/data/api/ttn.lorawan.v3/messages/JoinRequest.yml
  doc/data/api/ttn.lorawan.v3/messages/ProvisionEndDevicesRequest.IdentifiersFromData.yml
  doc/data/api/ttn.lorawan.v3/messages/ProvisionEndDevicesRequest.IdentifiersList.yml
  doc/data/api/ttn.lorawan.v3/messages/ProvisionEndDevicesRequest.IdentifiersRange.yml
  doc/data/api/ttn.lorawan.v3/messages/Session.yml
  doc/data/api/ttn.lorawan.v3/messages/SessionKeyRequest.yml
Labels: documentation, release

#896 doc: Update Kaa integration section
  doc/content/integrations/cloud-integrations/kaa/_index.md
  doc/content/integrations/cloud-integrations/kaa/index.md
  doc/content/integrations/cloud-integrations/kaa/kaa-create-app-integration.png
  doc/content/integrations/cloud-integrations/kaa/kaa-create-app-version.png
  doc/content/integrations/cloud-integrations/kaa/kaa-create-application.png
  doc/content/integrations/cloud-integrations/kaa/kaa-create-dev-integration.png
  doc/content/integrations/cloud-integrations/kaa/kaa-created-endpoint.png
  doc/content/integrations/cloud-integrations/kaa/kaa-dev-integration.png
  doc/content/integrations/cloud-integrations/kaa/kaa-dev-integrations.png
  doc/content/integrations/cloud-integrations/kaa/kaa-endpoint-data.png
  doc/content/integrations/cloud-integrations/kaa/kaa-endpoint-no-data.png
  doc/content/integrations/cloud-integrations/kaa/kaa-epts-autoextract-config.png
  doc/content/integrations/cloud-integrations/kaa/kaa-epts-enable-auto-extraction.png
  doc/content/integrations/cloud-integrations/kaa/ttn-connection-information.png
  doc/content/integrations/cloud-integrations/kaa/ttn-generate-api-key.png
Labels: documentation
