Repository TheThingsIndustries/lorawan-stack-docs, pull requests merged in 2023-08, with the labels that each got.

#1146 doc: Update ADR documentation
  doc/content/reference/adr/_index.md
Labels: documentation

#1156 doc: Update Cloud Studio screenshots
  doc/content/integrations/cloud-integrations/cloudstudio/access-token.png
  doc/content/integrations/cloud-integrations/cloudstudio/add-dashboard.png
  doc/content/integrations/cloud-integrations/cloudstudio/add-device.png
  doc/content/integrations/cloud-integrations/cloudstudio/configuration.png
  doc/content/integrations/cloud-integrations/cloudstudio/copy-token.png
  doc/content/integrations/cloud-integrations/cloudstudio/creating-device-model.png
  doc/content/integrations/cloud-integrations/cloudstudio/dashboard.png
  doc/content/integrations/cloud-integrations/cloudstudio/device-model.png
  doc/content/integrations/cloud-integrations/cloudstudio/edit-device-model.png
  doc/content/integrations/cloud-integrations/cloudstudio/index.md
  doc/content/integrations/cloud-integrations/cloudstudio/scripts-configuration.png
  doc/content/integrations/cloud-integrations/cloudstudio/scripts-payload-parser.png
  doc/content/integrations/cloud-integrations/cloudstudio/select-widget.png
  doc/content/integrations/cloud-integrations/cloudstudio/widget-settings.png
Labels: documentation

#1119 Redesign home page UI
  .gitignore
  doc/content/whats-new/3.25.2.md
  doc/content/whats-new/3.26.0.md
  doc/content/whats-new/3.26.2.md
  doc/package.json
  doc/static/img/doc-pattern.png
  doc/static/img/doc-whats-new-bg.png
  doc/themes/the-things-stack/assets/css/pages/homepage.scss
  doc/themes/the-things-stack/assets/css/theme.scss
  doc/themes/the-things-stack/assets/css/vendor/bulma/sass/components/navbar.sass
  doc/themes/the-things-stack/assets/js/theme.js
  doc/themes/the-things-stack/layouts/_default/baseof.html
  doc/themes/the-things-stack/layouts/index.html
  doc/themes/the-things-stack/layouts/partials/footer/footer.html
  doc/themes/the-things-stack/layouts/partials/head/head.html
  doc/themes/the-things-stack/layouts/partials/header/nav.html
  doc/themes/the-things-stack/layouts/partials/whats-new.html
  doc/yarn.lock
  go.mod
  go.sum
Labels: documentation, status/blocked, ui/web

#1160 Add thumbnail to the docs
  doc/static/docs-thumbnail.png
  doc/themes/the-things-stack/layouts/partials/head/head.html
Labels: ui/web

#1153 Documentation on Telemetry procedures
  doc/content/reference/telemetry/_index.md
  doc/content/reference/telemetry/cli.md
  doc/content/reference/telemetry/identity_server.md
Labels: c/identity server, ui/cli
